
# ----------------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.10.8, generator: @autorest/powershell@4.0.752)
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# ----------------------------------------------------------------------------------

<#
.Synopsis
Create an in-memory object for FsLogixCloudCacheRegistrySettings.
.Description
Create an in-memory object for FsLogixCloudCacheRegistrySettings.

.Outputs
NmePowershell.Models.FsLogixCloudCacheRegistrySettings

#>
function New-NmeFsLogixCloudCacheRegistrySettingsModel {
    [NmePowershell.ModelCmdletAttribute()]
    [OutputType('NmePowershell.Models.FsLogixCloudCacheRegistrySettings')]
    [CmdletBinding(PositionalBinding=$false)]
    Param(

        [Parameter()]
        [string]
        $Common,
        [Parameter()]
        [string]
        $OfficeContainer,
        [Parameter()]
        [string]
        $ProfileContainer
    )

    process {
        $Object = [NmePowershell.Models.FsLogixCloudCacheRegistrySettings]::New()

        if ($PSBoundParameters.ContainsKey('Common')) {
            $Object.Common = $Common
        }
        if ($PSBoundParameters.ContainsKey('OfficeContainer')) {
            $Object.OfficeContainer = $OfficeContainer
        }
        if ($PSBoundParameters.ContainsKey('ProfileContainer')) {
            $Object.ProfileContainer = $ProfileContainer
        }
        return $Object
    }
}

