
# ----------------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.10.8, generator: @autorest/powershell@4.0.752)
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# ----------------------------------------------------------------------------------

<#
.Synopsis
Create an in-memory object for AutoScaleProfileSchedule.
.Description
Create an in-memory object for AutoScaleProfileSchedule.

.Outputs
NmePowershell.Models.AutoScaleProfileSchedule

#>
function New-NmeAutoScaleProfileScheduleModel {
    [NmePowershell.ModelCmdletAttribute()]
    [OutputType('NmePowershell.Models.AutoScaleProfileSchedule')]
    [CmdletBinding(PositionalBinding=$false)]
    Param(

        [Parameter()]
        [NmePowershell.Models.IAutoScaleProfileScheduleDateRange[]]
        $DateRanges,
        [Parameter(Mandatory)]
        [bool]
        $IsEnabled,
        [Parameter()]
        [NmePowershell.PSArgumentCompleterAttribute("0", "1", "2", "3", "4", "5", "6")]
        [int[]]
        $WeekDays
    )

    process {
        $Object = [NmePowershell.Models.AutoScaleProfileSchedule]::New()

        if ($PSBoundParameters.ContainsKey('DateRanges')) {
            $Object.DateRanges = $DateRanges
        }
        if ($PSBoundParameters.ContainsKey('IsEnabled')) {
            $Object.IsEnabled = $IsEnabled
        }
        if ($PSBoundParameters.ContainsKey('WeekDays')) {
            $Object.WeekDays = $WeekDays
        }
        return $Object
    }
}

