
# ----------------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.10.8, generator: @autorest/powershell@4.0.752)
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# ----------------------------------------------------------------------------------

<#
.Synopsis
Create an in-memory object for SessionHostRemove.
.Description
Create an in-memory object for SessionHostRemove.

.Outputs
NmePowershell.Models.SessionHostRemove

#>
function New-NmeSessionHostRemoveModel {
    [NmePowershell.ModelCmdletAttribute()]
    [OutputType('NmePowershell.Models.SessionHostRemove')]
    [CmdletBinding(PositionalBinding=$false)]
    Param(

        [Parameter()]
        [bool]
        $FailurePolicyCleanup,
        [Parameter()]
        [bool]
        $FailurePolicyRestart,
        [Parameter(Mandatory)]
        [bool]
        $JobPayloadForceRemoveWvdRecord,
        [Parameter(Mandatory)]
        [bool]
        $JobPayloadRemoveUsedVMName,
        [Parameter(Mandatory)]
        [bool]
        $JobPayloadSkipAdRemoval
    )

    process {
        $Object = [NmePowershell.Models.SessionHostRemove]::New()

        if ($PSBoundParameters.ContainsKey('FailurePolicyCleanup')) {
            $Object.FailurePolicyCleanup = $FailurePolicyCleanup
        }
        if ($PSBoundParameters.ContainsKey('FailurePolicyRestart')) {
            $Object.FailurePolicyRestart = $FailurePolicyRestart
        }
        if ($PSBoundParameters.ContainsKey('JobPayloadForceRemoveWvdRecord')) {
            $Object.JobPayloadForceRemoveWvdRecord = $JobPayloadForceRemoveWvdRecord
        }
        if ($PSBoundParameters.ContainsKey('JobPayloadRemoveUsedVMName')) {
            $Object.JobPayloadRemoveUsedVMName = $JobPayloadRemoveUsedVMName
        }
        if ($PSBoundParameters.ContainsKey('JobPayloadSkipAdRemoval')) {
            $Object.JobPayloadSkipAdRemoval = $JobPayloadSkipAdRemoval
        }
        return $Object
    }
}

