
# ----------------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.10.8, generator: @autorest/powershell@4.0.752)
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# ----------------------------------------------------------------------------------

<#
.Synopsis
Create an in-memory object for AppAttachImageUpdate.
.Description
Create an in-memory object for AppAttachImageUpdate.

.Outputs
NmePowershell.Models.AppAttachImageUpdate

#>
function New-NmeAppAttachImageUpdateModel {
    [NmePowershell.ModelCmdletAttribute()]
    [OutputType('NmePowershell.Models.AppAttachImageUpdate')]
    [CmdletBinding(PositionalBinding=$false)]
    Param(

        [Parameter()]
        [string]
        $Description,
        [Parameter()]
        [string]
        $ImageName
    )

    process {
        $Object = [NmePowershell.Models.AppAttachImageUpdate]::New()

        if ($PSBoundParameters.ContainsKey('Description')) {
            $Object.Description = $Description
        }
        if ($PSBoundParameters.ContainsKey('ImageName')) {
            $Object.ImageName = $ImageName
        }
        return $Object
    }
}

