
# ----------------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.10.8, generator: @autorest/powershell@4.0.752)
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# ----------------------------------------------------------------------------------

<#
.Synopsis
Create an in-memory object for FsLogixProperties.
.Description
Create an in-memory object for FsLogixProperties.

.Outputs
NmePowershell.Models.FsLogixProperties

#>
function New-NmeFsLogixPropertiesModel {
    [NmePowershell.ModelCmdletAttribute()]
    [OutputType('NmePowershell.Models.FsLogixProperties')]
    [CmdletBinding(PositionalBinding=$false)]
    Param(

        [Parameter()]
        [string]
        $AppServiceRegistryOptionRegistryOptions,
        [Parameter()]
        [NmePowershell.PSArgumentCompleterAttribute("None", "Apply")]
        [string]
        $AppServiceRegistryOptionRegistryOptionsMode,
        [Parameter(Mandatory)]
        [bool]
        $CloudCache,
        [Parameter()]
        [string]
        $CloudCacheRegistryOptionCommon,
        [Parameter()]
        [string]
        $CloudCacheRegistryOptionOfficeContainer,
        [Parameter()]
        [string]
        $CloudCacheRegistryOptionProfileContainer,
        [Parameter(Mandatory)]
        [bool]
        $EntraIdKerberos,
        [Parameter()]
        [string[]]
        $ExclusionExcludedDomainAccounts,
        [Parameter(Mandatory)]
        [NmePowershell.PSArgumentCompleterAttribute("None", "Admins")]
        [string]
        $ExclusionMode,
        [Parameter(Mandatory)]
        [bool]
        $InstallerForceUpdate,
        [Parameter(Mandatory)]
        [string]
        $InstallerVersion,
        [Parameter()]
        [string]
        $LogRegistryOptionRegistryOptions,
        [Parameter()]
        [NmePowershell.PSArgumentCompleterAttribute("None", "Apply")]
        [string]
        $LogRegistryOptionRegistryOptionsMode,
        [Parameter(Mandatory)]
        [string[]]
        $OfficeContainerLocations,
        [Parameter(Mandatory)]
        [string]
        $OfficeContainerOptions,
        [Parameter(Mandatory)]
        [bool]
        $PageBlobs,
        [Parameter(Mandatory)]
        [string[]]
        $ProfileContainerLocations,
        [Parameter(Mandatory)]
        [string]
        $ProfileContainerOptions,
        [Parameter(Mandatory)]
        [string]
        $RedirectionsXml
    )

    process {
        $Object = [NmePowershell.Models.FsLogixProperties]::New()

        if ($PSBoundParameters.ContainsKey('AppServiceRegistryOptionRegistryOptions')) {
            $Object.AppServiceRegistryOptionRegistryOptions = $AppServiceRegistryOptionRegistryOptions
        }
        if ($PSBoundParameters.ContainsKey('AppServiceRegistryOptionRegistryOptionsMode')) {
            $Object.AppServiceRegistryOptionRegistryOptionsMode = $AppServiceRegistryOptionRegistryOptionsMode
        }
        if ($PSBoundParameters.ContainsKey('CloudCache')) {
            $Object.CloudCache = $CloudCache
        }
        if ($PSBoundParameters.ContainsKey('CloudCacheRegistryOptionCommon')) {
            $Object.CloudCacheRegistryOptionCommon = $CloudCacheRegistryOptionCommon
        }
        if ($PSBoundParameters.ContainsKey('CloudCacheRegistryOptionOfficeContainer')) {
            $Object.CloudCacheRegistryOptionOfficeContainer = $CloudCacheRegistryOptionOfficeContainer
        }
        if ($PSBoundParameters.ContainsKey('CloudCacheRegistryOptionProfileContainer')) {
            $Object.CloudCacheRegistryOptionProfileContainer = $CloudCacheRegistryOptionProfileContainer
        }
        if ($PSBoundParameters.ContainsKey('EntraIdKerberos')) {
            $Object.EntraIdKerberos = $EntraIdKerberos
        }
        if ($PSBoundParameters.ContainsKey('ExclusionExcludedDomainAccounts')) {
            $Object.ExclusionExcludedDomainAccounts = $ExclusionExcludedDomainAccounts
        }
        if ($PSBoundParameters.ContainsKey('ExclusionMode')) {
            $Object.ExclusionMode = $ExclusionMode
        }
        if ($PSBoundParameters.ContainsKey('InstallerForceUpdate')) {
            $Object.InstallerForceUpdate = $InstallerForceUpdate
        }
        if ($PSBoundParameters.ContainsKey('InstallerVersion')) {
            $Object.InstallerVersion = $InstallerVersion
        }
        if ($PSBoundParameters.ContainsKey('LogRegistryOptionRegistryOptions')) {
            $Object.LogRegistryOptionRegistryOptions = $LogRegistryOptionRegistryOptions
        }
        if ($PSBoundParameters.ContainsKey('LogRegistryOptionRegistryOptionsMode')) {
            $Object.LogRegistryOptionRegistryOptionsMode = $LogRegistryOptionRegistryOptionsMode
        }
        if ($PSBoundParameters.ContainsKey('OfficeContainerLocations')) {
            $Object.OfficeContainerLocations = $OfficeContainerLocations
        }
        if ($PSBoundParameters.ContainsKey('OfficeContainerOptions')) {
            $Object.OfficeContainerOptions = $OfficeContainerOptions
        }
        if ($PSBoundParameters.ContainsKey('PageBlobs')) {
            $Object.PageBlobs = $PageBlobs
        }
        if ($PSBoundParameters.ContainsKey('ProfileContainerLocations')) {
            $Object.ProfileContainerLocations = $ProfileContainerLocations
        }
        if ($PSBoundParameters.ContainsKey('ProfileContainerOptions')) {
            $Object.ProfileContainerOptions = $ProfileContainerOptions
        }
        if ($PSBoundParameters.ContainsKey('RedirectionsXml')) {
            $Object.RedirectionsXml = $RedirectionsXml
        }
        return $Object
    }
}

