
# ----------------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.10.8, generator: @autorest/powershell@4.0.752)
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# ----------------------------------------------------------------------------------

<#
.Synopsis
Create an in-memory object for AppGroupUpdate.
.Description
Create an in-memory object for AppGroupUpdate.

.Outputs
NmePowershell.Models.AppGroupUpdate

#>
function New-NmeAppGroupUpdateModel {
    [NmePowershell.ModelCmdletAttribute()]
    [OutputType('NmePowershell.Models.AppGroupUpdate')]
    [CmdletBinding(PositionalBinding=$false)]
    Param(

        [Parameter()]
        [NmePowershell.Models.IAppGroupItemCreate[]]
        $Items,
        [Parameter()]
        [string]
        $Name
    )

    process {
        $Object = [NmePowershell.Models.AppGroupUpdate]::New()

        if ($PSBoundParameters.ContainsKey('Items')) {
            $Object.Items = $Items
        }
        if ($PSBoundParameters.ContainsKey('Name')) {
            $Object.Name = $Name
        }
        return $Object
    }
}

