
# ----------------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.10.8, generator: @autorest/powershell@4.0.752)
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# ----------------------------------------------------------------------------------

<#
.Synopsis
Create an in-memory object for ScheduleConfigurationCreate.
.Description
Create an in-memory object for ScheduleConfigurationCreate.

.Outputs
NmePowershell.Models.ScheduleConfigurationCreate

#>
function New-NmeScheduleConfigurationCreateModel {
    [NmePowershell.ModelCmdletAttribute()]
    [OutputType('NmePowershell.Models.ScheduleConfigurationCreate')]
    [CmdletBinding(PositionalBinding=$false)]
    Param(

        [Parameter()]
        [NmePowershell.PSArgumentCompleterAttribute("0", "1", "2", "3", "4", "5", "6")]
        [int]
        $DayOfWeek,
        [Parameter()]
        [NmePowershell.PSArgumentCompleterAttribute("First", "Second", "Third", "Fourth", "Last")]
        [string]
        $DayOfWeekNumber,
        [Parameter()]
        [string]
        $Description,
        [Parameter()]
        [string]
        $Name,
        [Parameter()]
        [int]
        $OffsetInDays,
        [Parameter(Mandatory)]
        [NmePowershell.PSArgumentCompleterAttribute("Once", "Daily", "Weekly", "Monthly", "Hourly", "PatchTuesday")]
        [string]
        $ScheduleRecurrenceType,
        [Parameter(Mandatory)]
        [System.DateTime]
        $StartDate,
        [Parameter(Mandatory)]
        [int]
        $StartHour,
        [Parameter(Mandatory)]
        [int]
        $StartMinutes,
        [Parameter(Mandatory)]
        [string]
        $TimeZoneId
    )

    process {
        $Object = [NmePowershell.Models.ScheduleConfigurationCreate]::New()

        if ($PSBoundParameters.ContainsKey('DayOfWeek')) {
            $Object.DayOfWeek = $DayOfWeek
        }
        if ($PSBoundParameters.ContainsKey('DayOfWeekNumber')) {
            $Object.DayOfWeekNumber = $DayOfWeekNumber
        }
        if ($PSBoundParameters.ContainsKey('Description')) {
            $Object.Description = $Description
        }
        if ($PSBoundParameters.ContainsKey('Name')) {
            $Object.Name = $Name
        }
        if ($PSBoundParameters.ContainsKey('OffsetInDays')) {
            $Object.OffsetInDays = $OffsetInDays
        }
        if ($PSBoundParameters.ContainsKey('ScheduleRecurrenceType')) {
            $Object.ScheduleRecurrenceType = $ScheduleRecurrenceType
        }
        if ($PSBoundParameters.ContainsKey('StartDate')) {
            $Object.StartDate = $StartDate
        }
        if ($PSBoundParameters.ContainsKey('StartHour')) {
            $Object.StartHour = $StartHour
        }
        if ($PSBoundParameters.ContainsKey('StartMinutes')) {
            $Object.StartMinutes = $StartMinutes
        }
        if ($PSBoundParameters.ContainsKey('TimeZoneId')) {
            $Object.TimeZoneId = $TimeZoneId
        }
        return $Object
    }
}

