
# ----------------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.10.8, generator: @autorest/powershell@4.0.752)
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# ----------------------------------------------------------------------------------

<#
.Synopsis
Create an in-memory object for AdObjectCreate.
.Description
Create an in-memory object for AdObjectCreate.

.Outputs
NmePowershell.Models.AdObjectCreate

#>
function New-NmeAdObjectCreateModel {
    [NmePowershell.ModelCmdletAttribute()]
    [OutputType('NmePowershell.Models.AdObjectCreate')]
    [CmdletBinding(PositionalBinding=$false)]
    Param(

        [Parameter(Mandatory)]
        [string]
        $Id,
        [Parameter(Mandatory)]
        [NmePowershell.PSArgumentCompleterAttribute("User", "Group")]
        [string]
        $ObjectType
    )

    process {
        $Object = [NmePowershell.Models.AdObjectCreate]::New()

        if ($PSBoundParameters.ContainsKey('Id')) {
            $Object.Id = $Id
        }
        if ($PSBoundParameters.ContainsKey('ObjectType')) {
            $Object.ObjectType = $ObjectType
        }
        return $Object
    }
}

