
# ----------------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.10.8, generator: @autorest/powershell@4.0.752)
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# ----------------------------------------------------------------------------------

<#
.Synopsis
Create an in-memory object for NetAppFilesPreStageConfig.
.Description
Create an in-memory object for NetAppFilesPreStageConfig.

.Outputs
NmePowershell.Models.NetAppFilesPreStageConfig

#>
function New-NmeNetAppFilesPreStageConfigModel {
    [NmePowershell.ModelCmdletAttribute()]
    [OutputType('NmePowershell.Models.NetAppFilesPreStageConfig')]
    [CmdletBinding(PositionalBinding=$false)]
    Param(

        [Parameter(Mandatory)]
        [bool]
        $IsEnabled,
        [Parameter()]
        [string]
        $TimezoneId,
        [Parameter()]
        [NmePowershell.Models.INetAppFilesWorkTimeSet[]]
        $WorkTimeSets
    )

    process {
        $Object = [NmePowershell.Models.NetAppFilesPreStageConfig]::New()

        if ($PSBoundParameters.ContainsKey('IsEnabled')) {
            $Object.IsEnabled = $IsEnabled
        }
        if ($PSBoundParameters.ContainsKey('TimezoneId')) {
            $Object.TimezoneId = $TimezoneId
        }
        if ($PSBoundParameters.ContainsKey('WorkTimeSets')) {
            $Object.WorkTimeSets = $WorkTimeSets
        }
        return $Object
    }
}

