
# ----------------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.10.8, generator: @autorest/powershell@4.0.752)
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# ----------------------------------------------------------------------------------

<#
.Synopsis
Create an in-memory object for VmSecurityProfile.
.Description
Create an in-memory object for VmSecurityProfile.

.Outputs
NmePowershell.Models.VmSecurityProfile

#>
function New-NmeVmSecurityProfileModel {
    [NmePowershell.ModelCmdletAttribute()]
    [OutputType('NmePowershell.Models.VmSecurityProfile')]
    [CmdletBinding(PositionalBinding=$false)]
    Param(

        [Parameter()]
        [bool]
        $SecureBootEnabled,
        [Parameter(Mandatory)]
        [NmePowershell.PSArgumentCompleterAttribute("None", "TrustedLaunch", "Confidential")]
        [string]
        $SecurityType,
        [Parameter()]
        [bool]
        $VTpmEnabled
    )

    process {
        $Object = [NmePowershell.Models.VmSecurityProfile]::New()

        if ($PSBoundParameters.ContainsKey('SecureBootEnabled')) {
            $Object.SecureBootEnabled = $SecureBootEnabled
        }
        if ($PSBoundParameters.ContainsKey('SecurityType')) {
            $Object.SecurityType = $SecurityType
        }
        if ($PSBoundParameters.ContainsKey('VTpmEnabled')) {
            $Object.VTpmEnabled = $VTpmEnabled
        }
        return $Object
    }
}

