
# ----------------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.10.8, generator: @autorest/powershell@4.0.752)
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# ----------------------------------------------------------------------------------

<#
.Synopsis
Create an in-memory object for UserCostAttributionConfigurationUpdate.
.Description
Create an in-memory object for UserCostAttributionConfigurationUpdate.

.Outputs
NmePowershell.Models.UserCostAttributionConfigurationUpdate

#>
function New-NmeUserCostAttributionConfigurationUpdateModel {
    [NmePowershell.ModelCmdletAttribute()]
    [OutputType('NmePowershell.Models.UserCostAttributionConfigurationUpdate')]
    [CmdletBinding(PositionalBinding=$false)]
    Param(

        [Parameter()]
        [NmePowershell.PSArgumentCompleterAttribute("Uniform", "Proportional", "Unallocated")]
        [string]
        $DefaultReportType,
        [Parameter()]
        [string]
        $DisplayName,
        [Parameter()]
        [bool]
        $IsDefault
    )

    process {
        $Object = [NmePowershell.Models.UserCostAttributionConfigurationUpdate]::New()

        if ($PSBoundParameters.ContainsKey('DefaultReportType')) {
            $Object.DefaultReportType = $DefaultReportType
        }
        if ($PSBoundParameters.ContainsKey('DisplayName')) {
            $Object.DisplayName = $DisplayName
        }
        if ($PSBoundParameters.ContainsKey('IsDefault')) {
            $Object.IsDefault = $IsDefault
        }
        return $Object
    }
}

