
# ----------------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.10.8, generator: @autorest/powershell@4.0.752)
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# ----------------------------------------------------------------------------------

<#
.Synopsis
Create an in-memory object for SelfServiceDiskSize.
.Description
Create an in-memory object for SelfServiceDiskSize.

.Outputs
NmePowershell.Models.SelfServiceDiskSize

#>
function New-NmeSelfServiceDiskSizeModel {
    [NmePowershell.ModelCmdletAttribute()]
    [OutputType('NmePowershell.Models.SelfServiceDiskSize')]
    [CmdletBinding(PositionalBinding=$false)]
    Param(

        [Parameter(Mandatory)]
        [int]
        $SizeGb,
        [Parameter(Mandatory)]
        [string]
        $Sku
    )

    process {
        $Object = [NmePowershell.Models.SelfServiceDiskSize]::New()

        if ($PSBoundParameters.ContainsKey('SizeGb')) {
            $Object.SizeGb = $SizeGb
        }
        if ($PSBoundParameters.ContainsKey('Sku')) {
            $Object.Sku = $Sku
        }
        return $Object
    }
}

