
# ----------------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.10.8, generator: @autorest/powershell@4.0.752)
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# ----------------------------------------------------------------------------------

<#
.Synopsis
Create an in-memory object for PortalNotificationCreate.
.Description
Create an in-memory object for PortalNotificationCreate.

.Outputs
NmePowershell.Models.PortalNotificationCreate

#>
function New-NmePortalNotificationCreateModel {
    [NmePowershell.ModelCmdletAttribute()]
    [OutputType('NmePowershell.Models.PortalNotificationCreate')]
    [CmdletBinding(PositionalBinding=$false)]
    Param(

        [Parameter()]
        [string]
        $HostPoolId,
        [Parameter(Mandatory)]
        [string]
        $HtmlText,
        [Parameter()]
        [System.DateTime]
        $PeriodEndDate,
        [Parameter()]
        [System.DateTime]
        $PeriodStartDate,
        [Parameter()]
        [string]
        $PeriodTimeZoneId,
        [Parameter(Mandatory)]
        [NmePowershell.PSArgumentCompleterAttribute("UserSelfServiceGlobal", "UserSelfServiceHostPool", "AdminConsoleGlobal", "LicenseUsageNotice", "LicenseComplianceWarning")]
        [string]
        $Type
    )

    process {
        $Object = [NmePowershell.Models.PortalNotificationCreate]::New()

        if ($PSBoundParameters.ContainsKey('HostPoolId')) {
            $Object.HostPoolId = $HostPoolId
        }
        if ($PSBoundParameters.ContainsKey('HtmlText')) {
            $Object.HtmlText = $HtmlText
        }
        if ($PSBoundParameters.ContainsKey('PeriodEndDate')) {
            $Object.PeriodEndDate = $PeriodEndDate
        }
        if ($PSBoundParameters.ContainsKey('PeriodStartDate')) {
            $Object.PeriodStartDate = $PeriodStartDate
        }
        if ($PSBoundParameters.ContainsKey('PeriodTimeZoneId')) {
            $Object.PeriodTimeZoneId = $PeriodTimeZoneId
        }
        if ($PSBoundParameters.ContainsKey('Type')) {
            $Object.Type = $Type
        }
        return $Object
    }
}

