
# ----------------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.10.8, generator: @autorest/powershell@4.0.752)
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# ----------------------------------------------------------------------------------

<#
.Synopsis
Create an in-memory object for PersonalAutoGrowConfiguration.
.Description
Create an in-memory object for PersonalAutoGrowConfiguration.

.Outputs
NmePowershell.Models.PersonalAutoGrowConfiguration

#>
function New-NmePersonalAutoGrowConfigurationModel {
    [NmePowershell.ModelCmdletAttribute()]
    [OutputType('NmePowershell.Models.PersonalAutoGrowConfiguration')]
    [CmdletBinding(PositionalBinding=$false)]
    Param(

        [Parameter(Mandatory)]
        [int]
        $UnassignedThreshold,
        [Parameter(Mandatory)]
        [NmePowershell.PSArgumentCompleterAttribute("0", "1")]
        [int]
        $Unit
    )

    process {
        $Object = [NmePowershell.Models.PersonalAutoGrowConfiguration]::New()

        if ($PSBoundParameters.ContainsKey('UnassignedThreshold')) {
            $Object.UnassignedThreshold = $UnassignedThreshold
        }
        if ($PSBoundParameters.ContainsKey('Unit')) {
            $Object.Unit = $Unit
        }
        return $Object
    }
}

