
# ----------------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.10.8, generator: @autorest/powershell@4.0.752)
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# ----------------------------------------------------------------------------------

<#
.Synopsis
Create an in-memory object for LinkedSubscriptionUpdate.
.Description
Create an in-memory object for LinkedSubscriptionUpdate.

.Outputs
NmePowershell.Models.LinkedSubscriptionUpdate

#>
function New-NmeLinkedSubscriptionUpdateModel {
    [NmePowershell.ModelCmdletAttribute()]
    [OutputType('NmePowershell.Models.LinkedSubscriptionUpdate')]
    [CmdletBinding(PositionalBinding=$false)]
    Param(

        [Parameter()]
        [bool]
        $AvdEnabled,
        [Parameter()]
        [bool]
        $CostManagementEnabled
    )

    process {
        $Object = [NmePowershell.Models.LinkedSubscriptionUpdate]::New()

        if ($PSBoundParameters.ContainsKey('AvdEnabled')) {
            $Object.AvdEnabled = $AvdEnabled
        }
        if ($PSBoundParameters.ContainsKey('CostManagementEnabled')) {
            $Object.CostManagementEnabled = $CostManagementEnabled
        }
        return $Object
    }
}

