
# ----------------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.10.8, generator: @autorest/powershell@4.0.752)
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# ----------------------------------------------------------------------------------

<#
.Synopsis
Create an in-memory object for ScaleInTimeRestrictionConfiguration.
.Description
Create an in-memory object for ScaleInTimeRestrictionConfiguration.

.Outputs
NmePowershell.Models.ScaleInTimeRestrictionConfiguration

#>
function New-NmeScaleInTimeRestrictionConfigurationModel {
    [NmePowershell.ModelCmdletAttribute()]
    [OutputType('NmePowershell.Models.ScaleInTimeRestrictionConfiguration')]
    [CmdletBinding(PositionalBinding=$false)]
    Param(

        [Parameter(Mandatory)]
        [bool]
        $Enable,
        [Parameter(Mandatory)]
        [bool]
        $PutToDrainMode,
        [Parameter()]
        [int]
        $TimeRangeEndHour,
        [Parameter()]
        [int]
        $TimeRangeEndMinutes,
        [Parameter()]
        [int]
        $TimeRangeStartHour,
        [Parameter()]
        [int]
        $TimeRangeStartMinutes
    )

    process {
        $Object = [NmePowershell.Models.ScaleInTimeRestrictionConfiguration]::New()

        if ($PSBoundParameters.ContainsKey('Enable')) {
            $Object.Enable = $Enable
        }
        if ($PSBoundParameters.ContainsKey('PutToDrainMode')) {
            $Object.PutToDrainMode = $PutToDrainMode
        }
        if ($PSBoundParameters.ContainsKey('TimeRangeEndHour')) {
            $Object.TimeRangeEndHour = $TimeRangeEndHour
        }
        if ($PSBoundParameters.ContainsKey('TimeRangeEndMinutes')) {
            $Object.TimeRangeEndMinutes = $TimeRangeEndMinutes
        }
        if ($PSBoundParameters.ContainsKey('TimeRangeStartHour')) {
            $Object.TimeRangeStartHour = $TimeRangeStartHour
        }
        if ($PSBoundParameters.ContainsKey('TimeRangeStartMinutes')) {
            $Object.TimeRangeStartMinutes = $TimeRangeStartMinutes
        }
        return $Object
    }
}

