
# ----------------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.10.8, generator: @autorest/powershell@4.0.752)
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# ----------------------------------------------------------------------------------

<#
.Synopsis
Create an in-memory object for LinkedResourceGroupCreate.
.Description
Create an in-memory object for LinkedResourceGroupCreate.

.Outputs
NmePowershell.Models.LinkedResourceGroupCreate

#>
function New-NmeLinkedResourceGroupCreateModel {
    [NmePowershell.ModelCmdletAttribute()]
    [OutputType('NmePowershell.Models.LinkedResourceGroupCreate')]
    [CmdletBinding(PositionalBinding=$false)]
    Param(

        [Parameter(Mandatory)]
        [bool]
        $IsDefault
    )

    process {
        $Object = [NmePowershell.Models.LinkedResourceGroupCreate]::New()

        if ($PSBoundParameters.ContainsKey('IsDefault')) {
            $Object.IsDefault = $IsDefault
        }
        return $Object
    }
}

