
# ----------------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.10.8, generator: @autorest/powershell@4.0.752)
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# ----------------------------------------------------------------------------------

<#
.Synopsis
Create an in-memory object for UserDrivenConfiguration.
.Description
Create an in-memory object for UserDrivenConfiguration.

.Outputs
NmePowershell.Models.UserDrivenConfiguration

#>
function New-NmeUserDrivenConfigurationModel {
    [NmePowershell.ModelCmdletAttribute()]
    [OutputType('NmePowershell.Models.UserDrivenConfiguration')]
    [CmdletBinding(PositionalBinding=$false)]
    Param(

        [Parameter(Mandatory)]
        [bool]
        $BypassDrainMode,
        [Parameter(Mandatory)]
        [int]
        $MinAvailableSessions,
        [Parameter(Mandatory)]
        [int]
        $StopDelayMinutes
    )

    process {
        $Object = [NmePowershell.Models.UserDrivenConfiguration]::New()

        if ($PSBoundParameters.ContainsKey('BypassDrainMode')) {
            $Object.BypassDrainMode = $BypassDrainMode
        }
        if ($PSBoundParameters.ContainsKey('MinAvailableSessions')) {
            $Object.MinAvailableSessions = $MinAvailableSessions
        }
        if ($PSBoundParameters.ContainsKey('StopDelayMinutes')) {
            $Object.StopDelayMinutes = $StopDelayMinutes
        }
        return $Object
    }
}

