
# ----------------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.10.8, generator: @autorest/powershell@4.0.752)
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# ----------------------------------------------------------------------------------

<#
.Synopsis
Create an in-memory object for AutoScaleWorkingHoursConfigurationUpdate.
.Description
Create an in-memory object for AutoScaleWorkingHoursConfigurationUpdate.

.Outputs
NmePowershell.Models.AutoScaleWorkingHoursConfigurationUpdate

#>
function New-NmeAutoScaleWorkingHoursConfigurationUpdateModel {
    [NmePowershell.ModelCmdletAttribute()]
    [OutputType('NmePowershell.Models.AutoScaleWorkingHoursConfigurationUpdate')]
    [CmdletBinding(PositionalBinding=$false)]
    Param(

        [Parameter()]
        [NmePowershell.Models.IAutoHealConfigurationItem[]]
        $AutoHealConfigs,
        [Parameter()]
        [bool]
        $AutoHealEnable,
        [Parameter()]
        [bool]
        $AvdPropertyStartVMOnConnect,
        [Parameter()]
        [NmePowershell.Models.IAutoHealAction[]]
        $ConfigActions,
        [Parameter()]
        [NmePowershell.PSArgumentCompleterAttribute("WithoutSessions", "WithoutActive", "WithActive")]
        [string]
        $ConfigSessionCriteria,
        [Parameter()]
        [int]
        $ConfigStaleHeartbeatMinutes,
        [Parameter()]
        [int]
        $ConfigWaitMinutes,
        [Parameter()]
        [int]
        $ConfigWaitMinutesBeforeFirstAction,
        [Parameter()]
        [NmePowershell.PSArgumentCompleterAttribute("Available", "Unavailable", "Shutdown", "Disconnected", "Upgrading", "UpgradeFailed", "NoHeartbeat", "NotJoinedToDomain", "DomainTrustRelationshipLost", "SxSStackListenerNotReady", "FSLogixNotHealthy", "NeedsAssistance")]
        [string[]]
        $ConfigWvdStatuses,
        [Parameter()]
        [string]
        $MessagingMessage,
        [Parameter()]
        [int]
        $MessagingMinutesBeforeRemove,
        [Parameter()]
        [NmePowershell.PSArgumentCompleterAttribute("None", "Default", "Hybrid", "Automated")]
        [string]
        $OSDiskPreStageMode,
        [Parameter()]
        [NmePowershell.PSArgumentCompleterAttribute("All", "Assigned")]
        [string]
        $OSDiskPreStageTarget,
        [Parameter()]
        [NmePowershell.PSArgumentCompleterAttribute("OneTime", "Continuously", "Never")]
        [string]
        $PowerTimingPowerOffTiming,
        [Parameter()]
        [NmePowershell.PSArgumentCompleterAttribute("OneTime", "Continuously", "Never")]
        [string]
        $PowerTimingPowerOnTiming,
        [Parameter()]
        [NmePowershell.PSArgumentCompleterAttribute("All", "Assigned")]
        [string]
        $PowerTimingTargetHosts,
        [Parameter()]
        [NmePowershell.PSArgumentCompleterAttribute("High", "Medium", "Low")]
        [string]
        $ScaleInPolicyAggressiveness,
        [Parameter()]
        [int]
        $TimeIntervalDuration,
        [Parameter()]
        [int]
        $TimeIntervalHour,
        [Parameter()]
        [int]
        $TimeIntervalMinutes,
        [Parameter()]
        [NmePowershell.Models.IDynamicPoolTriggerInfo[]]
        $Triggers,
        [Parameter()]
        [NmePowershell.PSArgumentCompleterAttribute("0", "1", "2", "3", "4", "5", "6")]
        [int[]]
        $WorkingHourDays
    )

    process {
        $Object = [NmePowershell.Models.AutoScaleWorkingHoursConfigurationUpdate]::New()

        if ($PSBoundParameters.ContainsKey('AutoHealConfigs')) {
            $Object.AutoHealConfigs = $AutoHealConfigs
        }
        if ($PSBoundParameters.ContainsKey('AutoHealEnable')) {
            $Object.AutoHealEnable = $AutoHealEnable
        }
        if ($PSBoundParameters.ContainsKey('AvdPropertyStartVMOnConnect')) {
            $Object.AvdPropertyStartVMOnConnect = $AvdPropertyStartVMOnConnect
        }
        if ($PSBoundParameters.ContainsKey('ConfigActions')) {
            $Object.ConfigActions = $ConfigActions
        }
        if ($PSBoundParameters.ContainsKey('ConfigSessionCriteria')) {
            $Object.ConfigSessionCriteria = $ConfigSessionCriteria
        }
        if ($PSBoundParameters.ContainsKey('ConfigStaleHeartbeatMinutes')) {
            $Object.ConfigStaleHeartbeatMinutes = $ConfigStaleHeartbeatMinutes
        }
        if ($PSBoundParameters.ContainsKey('ConfigWaitMinutes')) {
            $Object.ConfigWaitMinutes = $ConfigWaitMinutes
        }
        if ($PSBoundParameters.ContainsKey('ConfigWaitMinutesBeforeFirstAction')) {
            $Object.ConfigWaitMinutesBeforeFirstAction = $ConfigWaitMinutesBeforeFirstAction
        }
        if ($PSBoundParameters.ContainsKey('ConfigWvdStatuses')) {
            $Object.ConfigWvdStatuses = $ConfigWvdStatuses
        }
        if ($PSBoundParameters.ContainsKey('MessagingMessage')) {
            $Object.MessagingMessage = $MessagingMessage
        }
        if ($PSBoundParameters.ContainsKey('MessagingMinutesBeforeRemove')) {
            $Object.MessagingMinutesBeforeRemove = $MessagingMinutesBeforeRemove
        }
        if ($PSBoundParameters.ContainsKey('OSDiskPreStageMode')) {
            $Object.OSDiskPreStageMode = $OSDiskPreStageMode
        }
        if ($PSBoundParameters.ContainsKey('OSDiskPreStageTarget')) {
            $Object.OSDiskPreStageTarget = $OSDiskPreStageTarget
        }
        if ($PSBoundParameters.ContainsKey('PowerTimingPowerOffTiming')) {
            $Object.PowerTimingPowerOffTiming = $PowerTimingPowerOffTiming
        }
        if ($PSBoundParameters.ContainsKey('PowerTimingPowerOnTiming')) {
            $Object.PowerTimingPowerOnTiming = $PowerTimingPowerOnTiming
        }
        if ($PSBoundParameters.ContainsKey('PowerTimingTargetHosts')) {
            $Object.PowerTimingTargetHosts = $PowerTimingTargetHosts
        }
        if ($PSBoundParameters.ContainsKey('ScaleInPolicyAggressiveness')) {
            $Object.ScaleInPolicyAggressiveness = $ScaleInPolicyAggressiveness
        }
        if ($PSBoundParameters.ContainsKey('TimeIntervalDuration')) {
            $Object.TimeIntervalDuration = $TimeIntervalDuration
        }
        if ($PSBoundParameters.ContainsKey('TimeIntervalHour')) {
            $Object.TimeIntervalHour = $TimeIntervalHour
        }
        if ($PSBoundParameters.ContainsKey('TimeIntervalMinutes')) {
            $Object.TimeIntervalMinutes = $TimeIntervalMinutes
        }
        if ($PSBoundParameters.ContainsKey('Triggers')) {
            $Object.Triggers = $Triggers
        }
        if ($PSBoundParameters.ContainsKey('WorkingHourDays')) {
            $Object.WorkingHourDays = $WorkingHourDays
        }
        return $Object
    }
}

