
# ----------------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.10.8, generator: @autorest/powershell@4.0.752)
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# ----------------------------------------------------------------------------------

<#
.Synopsis
Create an in-memory object for SessionHostCreateParams.
.Description
Create an in-memory object for SessionHostCreateParams.

.Outputs
NmePowershell.Models.SessionHostCreateParams

#>
function New-NmeSessionHostCreateParamsModel {
    [NmePowershell.ModelCmdletAttribute()]
    [OutputType('NmePowershell.Models.SessionHostCreateParams')]
    [CmdletBinding(PositionalBinding=$false)]
    Param(

        [Parameter()]
        [string]
        $HostDiskPerformanceTier,
        [Parameter(Mandatory)]
        [int]
        $HostDiskSize,
        [Parameter()]
        [NmePowershell.PSArgumentCompleterAttribute("CacheDisk", "ResourceDisk", "NvmeDisk")]
        [string]
        $HostEphemeralOSDiskPlacement,
        [Parameter(Mandatory)]
        [bool]
        $HostHasEphemeralOSDisk,
        [Parameter(Mandatory)]
        [string]
        $HostImage,
        [Parameter(Mandatory)]
        [string]
        $HostNetworkId,
        [Parameter(Mandatory)]
        [string]
        $HostStorageType,
        [Parameter(Mandatory)]
        [string]
        $HostSubnet,
        [Parameter(Mandatory)]
        [string]
        $HostVMSize,
        [Parameter()]
        [int]
        $HostsCount,
        [Parameter(HelpMessage="Dictionary of <string>.")]
        [NmePowershell.Models.ISessionHostCreateParamsTags]
        $Tags,
        [Parameter()]
        [string]
        $UserToAssign,
        [Parameter(Mandatory, HelpMessage="Define the name assigning behaviour.
        false: Host will have name with the exact 'Name' value;
        true:  Host will have name with the 'Name-{????}' value.")]
        [bool]
        $VMIdAddSuffix,
        [Parameter(Mandatory)]
        [string]
        $VMIdName,
        [Parameter(Mandatory)]
        [string]
        $VMIdResourceGroup,
        [Parameter(Mandatory)]
        [string]
        $VMIdSubscriptionId
    )

    process {
        $Object = [NmePowershell.Models.SessionHostCreateParams]::New()

        if ($PSBoundParameters.ContainsKey('HostDiskPerformanceTier')) {
            $Object.HostDiskPerformanceTier = $HostDiskPerformanceTier
        }
        if ($PSBoundParameters.ContainsKey('HostDiskSize')) {
            $Object.HostDiskSize = $HostDiskSize
        }
        if ($PSBoundParameters.ContainsKey('HostEphemeralOSDiskPlacement')) {
            $Object.HostEphemeralOSDiskPlacement = $HostEphemeralOSDiskPlacement
        }
        if ($PSBoundParameters.ContainsKey('HostHasEphemeralOSDisk')) {
            $Object.HostHasEphemeralOSDisk = $HostHasEphemeralOSDisk
        }
        if ($PSBoundParameters.ContainsKey('HostImage')) {
            $Object.HostImage = $HostImage
        }
        if ($PSBoundParameters.ContainsKey('HostNetworkId')) {
            $Object.HostNetworkId = $HostNetworkId
        }
        if ($PSBoundParameters.ContainsKey('HostStorageType')) {
            $Object.HostStorageType = $HostStorageType
        }
        if ($PSBoundParameters.ContainsKey('HostSubnet')) {
            $Object.HostSubnet = $HostSubnet
        }
        if ($PSBoundParameters.ContainsKey('HostVMSize')) {
            $Object.HostVMSize = $HostVMSize
        }
        if ($PSBoundParameters.ContainsKey('HostsCount')) {
            $Object.HostsCount = $HostsCount
        }
        if ($PSBoundParameters.ContainsKey('Tags')) {
            $Object.Tags = $Tags
        }
        if ($PSBoundParameters.ContainsKey('UserToAssign')) {
            $Object.UserToAssign = $UserToAssign
        }
        if ($PSBoundParameters.ContainsKey('VMIdAddSuffix')) {
            $Object.VMIdAddSuffix = $VMIdAddSuffix
        }
        if ($PSBoundParameters.ContainsKey('VMIdName')) {
            $Object.VMIdName = $VMIdName
        }
        if ($PSBoundParameters.ContainsKey('VMIdResourceGroup')) {
            $Object.VMIdResourceGroup = $VMIdResourceGroup
        }
        if ($PSBoundParameters.ContainsKey('VMIdSubscriptionId')) {
            $Object.VMIdSubscriptionId = $VMIdSubscriptionId
        }
        return $Object
    }
}

