
# ----------------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.10.8, generator: @autorest/powershell@4.0.752)
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# ----------------------------------------------------------------------------------

<#
.Synopsis
Create an in-memory object for AutoScaleProfileCreate.
.Description
Create an in-memory object for AutoScaleProfileCreate.

.Outputs
NmePowershell.Models.AutoScaleProfileCreate

#>
function New-NmeAutoScaleProfileCreateModel {
    [NmePowershell.ModelCmdletAttribute()]
    [OutputType('NmePowershell.Models.AutoScaleProfileCreate')]
    [CmdletBinding(PositionalBinding=$false)]
    Param(

        [Parameter()]
        [NmePowershell.Models.IAutoScaleDefaultConfiguration]
        $Default,
        [Parameter()]
        [string]
        $Description,
        [Parameter(Mandatory)]
        [NmePowershell.PSArgumentCompleterAttribute("Default", "WorkingHours", "UserDriven")]
        [string]
        $Mode,
        [Parameter(Mandatory)]
        [string]
        $Name,
        [Parameter()]
        [NmePowershell.Models.IAutoScaleUserDrivenConfigurationCreate]
        $UserDriven,
        [Parameter()]
        [NmePowershell.Models.IAutoScaleWorkingHoursConfiguration]
        $WorkingHours
    )

    process {
        $Object = [NmePowershell.Models.AutoScaleProfileCreate]::New()

        if ($PSBoundParameters.ContainsKey('Default')) {
            $Object.Default = $Default
        }
        if ($PSBoundParameters.ContainsKey('Description')) {
            $Object.Description = $Description
        }
        if ($PSBoundParameters.ContainsKey('Mode')) {
            $Object.Mode = $Mode
        }
        if ($PSBoundParameters.ContainsKey('Name')) {
            $Object.Name = $Name
        }
        if ($PSBoundParameters.ContainsKey('UserDriven')) {
            $Object.UserDriven = $UserDriven
        }
        if ($PSBoundParameters.ContainsKey('WorkingHours')) {
            $Object.WorkingHours = $WorkingHours
        }
        return $Object
    }
}

