
# ----------------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.10.8, generator: @autorest/powershell@4.0.752)
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# ----------------------------------------------------------------------------------

<#
.Synopsis
Create an in-memory object for LinkedNetworkCreate.
.Description
Create an in-memory object for LinkedNetworkCreate.

.Outputs
NmePowershell.Models.LinkedNetworkCreate

#>
function New-NmeLinkedNetworkCreateModel {
    [NmePowershell.ModelCmdletAttribute()]
    [OutputType('NmePowershell.Models.LinkedNetworkCreate')]
    [CmdletBinding(PositionalBinding=$false)]
    Param(

        [Parameter(Mandatory)]
        [string]
        $NetworkName,
        [Parameter(Mandatory)]
        [string]
        $ResourceGroupName,
        [Parameter(Mandatory)]
        [string]
        $SubnetName,
        [Parameter(Mandatory)]
        [string]
        $SubscriptionId
    )

    process {
        $Object = [NmePowershell.Models.LinkedNetworkCreate]::New()

        if ($PSBoundParameters.ContainsKey('NetworkName')) {
            $Object.NetworkName = $NetworkName
        }
        if ($PSBoundParameters.ContainsKey('ResourceGroupName')) {
            $Object.ResourceGroupName = $ResourceGroupName
        }
        if ($PSBoundParameters.ContainsKey('SubnetName')) {
            $Object.SubnetName = $SubnetName
        }
        if ($PSBoundParameters.ContainsKey('SubscriptionId')) {
            $Object.SubscriptionId = $SubscriptionId
        }
        return $Object
    }
}

