
# ----------------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.10.8, generator: @autorest/powershell@4.0.752)
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# ----------------------------------------------------------------------------------

<#
.Synopsis
Create an in-memory object for AutoScaleProfileScheduleDateRange.
.Description
Create an in-memory object for AutoScaleProfileScheduleDateRange.

.Outputs
NmePowershell.Models.AutoScaleProfileScheduleDateRange

#>
function New-NmeAutoScaleProfileScheduleDateRangeModel {
    [NmePowershell.ModelCmdletAttribute()]
    [OutputType('NmePowershell.Models.AutoScaleProfileScheduleDateRange')]
    [CmdletBinding(PositionalBinding=$false)]
    Param(

        [Parameter(Mandatory)]
        [System.DateTime]
        $EndDate,
        [Parameter(Mandatory)]
        [System.DateTime]
        $StartDate
    )

    process {
        $Object = [NmePowershell.Models.AutoScaleProfileScheduleDateRange]::New()

        if ($PSBoundParameters.ContainsKey('EndDate')) {
            $Object.EndDate = $EndDate
        }
        if ($PSBoundParameters.ContainsKey('StartDate')) {
            $Object.StartDate = $StartDate
        }
        return $Object
    }
}

