
# ----------------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.10.8, generator: @autorest/powershell@4.0.752)
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# ----------------------------------------------------------------------------------

<#
.Synopsis
Create an in-memory object for HostPoolControlUpSecondaryConfig.
.Description
Create an in-memory object for HostPoolControlUpSecondaryConfig.

.Outputs
NmePowershell.Models.HostPoolControlUpSecondaryConfig

#>
function New-NmeHostPoolControlUpSecondaryConfigModel {
    [NmePowershell.ModelCmdletAttribute()]
    [OutputType('NmePowershell.Models.HostPoolControlUpSecondaryConfig')]
    [CmdletBinding(PositionalBinding=$false)]
    Param(

        [Parameter()]
        [string]
        $DnsZone,
        [Parameter(Mandatory)]
        [bool]
        $Enabled,
        [Parameter()]
        [string]
        $Folder,
        [Parameter()]
        [string[]]
        $Monitors,
        [Parameter()]
        [string]
        $Site
    )

    process {
        $Object = [NmePowershell.Models.HostPoolControlUpSecondaryConfig]::New()

        if ($PSBoundParameters.ContainsKey('DnsZone')) {
            $Object.DnsZone = $DnsZone
        }
        if ($PSBoundParameters.ContainsKey('Enabled')) {
            $Object.Enabled = $Enabled
        }
        if ($PSBoundParameters.ContainsKey('Folder')) {
            $Object.Folder = $Folder
        }
        if ($PSBoundParameters.ContainsKey('Monitors')) {
            $Object.Monitors = $Monitors
        }
        if ($PSBoundParameters.ContainsKey('Site')) {
            $Object.Site = $Site
        }
        return $Object
    }
}

