
# ----------------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.10.8, generator: @autorest/powershell@4.0.752)
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# ----------------------------------------------------------------------------------

<#
.Synopsis
Create an in-memory object for AutoScaleProfileUpdate.
.Description
Create an in-memory object for AutoScaleProfileUpdate.

.Outputs
NmePowershell.Models.AutoScaleProfileUpdate

#>
function New-NmeAutoScaleProfileUpdateModel {
    [NmePowershell.ModelCmdletAttribute()]
    [OutputType('NmePowershell.Models.AutoScaleProfileUpdate')]
    [CmdletBinding(PositionalBinding=$false)]
    Param(

        [Parameter()]
        [NmePowershell.Models.IAutoScaleDefaultConfigurationUpdate]
        $Default,
        [Parameter()]
        [string]
        $Description,
        [Parameter()]
        [string]
        $Name,
        [Parameter()]
        [NmePowershell.Models.IAutoScaleUserDrivenConfigurationUpdate]
        $UserDriven,
        [Parameter()]
        [NmePowershell.Models.IAutoScaleWorkingHoursConfigurationUpdate]
        $WorkingHours
    )

    process {
        $Object = [NmePowershell.Models.AutoScaleProfileUpdate]::New()

        if ($PSBoundParameters.ContainsKey('Default')) {
            $Object.Default = $Default
        }
        if ($PSBoundParameters.ContainsKey('Description')) {
            $Object.Description = $Description
        }
        if ($PSBoundParameters.ContainsKey('Name')) {
            $Object.Name = $Name
        }
        if ($PSBoundParameters.ContainsKey('UserDriven')) {
            $Object.UserDriven = $UserDriven
        }
        if ($PSBoundParameters.ContainsKey('WorkingHours')) {
            $Object.WorkingHours = $WorkingHours
        }
        return $Object
    }
}

