
# ----------------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.10.8, generator: @autorest/powershell@4.0.752)
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# ----------------------------------------------------------------------------------

<#
.Synopsis
Create an in-memory object for AppGroupCreate.
.Description
Create an in-memory object for AppGroupCreate.

.Outputs
NmePowershell.Models.AppGroupCreate

#>
function New-NmeAppGroupCreateModel {
    [NmePowershell.ModelCmdletAttribute()]
    [OutputType('NmePowershell.Models.AppGroupCreate')]
    [CmdletBinding(PositionalBinding=$false)]
    Param(

        [Parameter(Mandatory)]
        [NmePowershell.Models.IAppGroupItemCreate[]]
        $Items,
        [Parameter(Mandatory)]
        [string]
        $Name
    )

    process {
        $Object = [NmePowershell.Models.AppGroupCreate]::New()

        if ($PSBoundParameters.ContainsKey('Items')) {
            $Object.Items = $Items
        }
        if ($PSBoundParameters.ContainsKey('Name')) {
            $Object.Name = $Name
        }
        return $Object
    }
}

