
# ----------------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.10.8, generator: @autorest/powershell@4.0.752)
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# ----------------------------------------------------------------------------------

<#
.Synopsis
Create an in-memory object for HostPoolRdpShortpathProperties.
.Description
Create an in-memory object for HostPoolRdpShortpathProperties.

.Outputs
NmePowershell.Models.HostPoolRdpShortpathProperties

#>
function New-NmeHostPoolRdpShortpathPropertiesModel {
    [NmePowershell.ModelCmdletAttribute()]
    [OutputType('NmePowershell.Models.HostPoolRdpShortpathProperties')]
    [CmdletBinding(PositionalBinding=$false)]
    Param(

        [Parameter(Mandatory)]
        [NmePowershell.PSArgumentCompleterAttribute("Unknown", "Default", "Disabled", "Enabled")]
        [string]
        $DirectUdp,
        [Parameter(Mandatory)]
        [NmePowershell.PSArgumentCompleterAttribute("Unknown", "Default", "Disabled", "Enabled")]
        [string]
        $ManagedPrivateUdp,
        [Parameter(Mandatory)]
        [NmePowershell.PSArgumentCompleterAttribute("Unknown", "Default", "Disabled", "Enabled")]
        [string]
        $PublicUdp,
        [Parameter(Mandatory)]
        [NmePowershell.PSArgumentCompleterAttribute("Unknown", "Default", "Disabled", "Enabled")]
        [string]
        $RelayUdp
    )

    process {
        $Object = [NmePowershell.Models.HostPoolRdpShortpathProperties]::New()

        if ($PSBoundParameters.ContainsKey('DirectUdp')) {
            $Object.DirectUdp = $DirectUdp
        }
        if ($PSBoundParameters.ContainsKey('ManagedPrivateUdp')) {
            $Object.ManagedPrivateUdp = $ManagedPrivateUdp
        }
        if ($PSBoundParameters.ContainsKey('PublicUdp')) {
            $Object.PublicUdp = $PublicUdp
        }
        if ($PSBoundParameters.ContainsKey('RelayUdp')) {
            $Object.RelayUdp = $RelayUdp
        }
        return $Object
    }
}

