
# ----------------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.10.8, generator: @autorest/powershell@4.0.752)
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# ----------------------------------------------------------------------------------

<#
.Synopsis
Create an in-memory object for AutoScaleSecondaryRegion.
.Description
Create an in-memory object for AutoScaleSecondaryRegion.

.Outputs
NmePowershell.Models.AutoScaleSecondaryRegion

#>
function New-NmeAutoScaleSecondaryRegionModel {
    [NmePowershell.ModelCmdletAttribute()]
    [OutputType('NmePowershell.Models.AutoScaleSecondaryRegion')]
    [CmdletBinding(PositionalBinding=$false)]
    Param(

        [Parameter()]
        [string]
        $ConfigNetworkId,
        [Parameter()]
        [string]
        $ConfigPrefix,
        [Parameter()]
        [string]
        $ConfigResourceGroupId,
        [Parameter()]
        [string]
        $ConfigSubnet,
        [Parameter(Mandatory)]
        [bool]
        $Enabled
    )

    process {
        $Object = [NmePowershell.Models.AutoScaleSecondaryRegion]::New()

        if ($PSBoundParameters.ContainsKey('ConfigNetworkId')) {
            $Object.ConfigNetworkId = $ConfigNetworkId
        }
        if ($PSBoundParameters.ContainsKey('ConfigPrefix')) {
            $Object.ConfigPrefix = $ConfigPrefix
        }
        if ($PSBoundParameters.ContainsKey('ConfigResourceGroupId')) {
            $Object.ConfigResourceGroupId = $ConfigResourceGroupId
        }
        if ($PSBoundParameters.ContainsKey('ConfigSubnet')) {
            $Object.ConfigSubnet = $ConfigSubnet
        }
        if ($PSBoundParameters.ContainsKey('Enabled')) {
            $Object.Enabled = $Enabled
        }
        return $Object
    }
}

