
# ----------------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.10.8, generator: @autorest/powershell@4.0.752)
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# ----------------------------------------------------------------------------------

<#
.Synopsis
Create an in-memory object for SharedAvdProperties.
.Description
Create an in-memory object for SharedAvdProperties.

.Outputs
NmePowershell.Models.SharedAvdProperties

#>
function New-NmeSharedAvdPropertiesModel {
    [NmePowershell.ModelCmdletAttribute()]
    [OutputType('NmePowershell.Models.SharedAvdProperties')]
    [CmdletBinding(PositionalBinding=$false)]
    Param(

        [Parameter(Mandatory)]
        [NmePowershell.PSArgumentCompleterAttribute("BreadthFirst", "DepthFirst", "Persistent", "MultiplePersistent")]
        [string]
        $LoadBalancing,
        [Parameter(Mandatory)]
        [int]
        $MaxSessionsPerHost,
        [Parameter(Mandatory)]
        [bool]
        $StartVMOnConnect
    )

    process {
        $Object = [NmePowershell.Models.SharedAvdProperties]::New()

        if ($PSBoundParameters.ContainsKey('LoadBalancing')) {
            $Object.LoadBalancing = $LoadBalancing
        }
        if ($PSBoundParameters.ContainsKey('MaxSessionsPerHost')) {
            $Object.MaxSessionsPerHost = $MaxSessionsPerHost
        }
        if ($PSBoundParameters.ContainsKey('StartVMOnConnect')) {
            $Object.StartVMOnConnect = $StartVMOnConnect
        }
        return $Object
    }
}

