
# ----------------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.10.8, generator: @autorest/powershell@4.0.752)
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# ----------------------------------------------------------------------------------

<#
.Synopsis
Create an in-memory object for JobFailurePolicy.
.Description
Create an in-memory object for JobFailurePolicy.

.Outputs
NmePowershell.Models.JobFailurePolicy

#>
function New-NmeJobFailurePolicyModel {
    [NmePowershell.ModelCmdletAttribute()]
    [OutputType('NmePowershell.Models.JobFailurePolicy')]
    [CmdletBinding(PositionalBinding=$false)]
    Param(

        [Parameter()]
        [bool]
        $Cleanup,
        [Parameter()]
        [bool]
        $Restart
    )

    process {
        $Object = [NmePowershell.Models.JobFailurePolicy]::New()

        if ($PSBoundParameters.ContainsKey('Cleanup')) {
            $Object.Cleanup = $Cleanup
        }
        if ($PSBoundParameters.ContainsKey('Restart')) {
            $Object.Restart = $Restart
        }
        return $Object
    }
}

