
# ----------------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.10.8, generator: @autorest/powershell@4.0.752)
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# ----------------------------------------------------------------------------------

<#
.Synopsis
Create an in-memory object for NotificationConditionUpdate.
.Description
Create an in-memory object for NotificationConditionUpdate.

.Outputs
NmePowershell.Models.NotificationConditionUpdate

#>
function New-NmeNotificationConditionUpdateModel {
    [NmePowershell.ModelCmdletAttribute()]
    [OutputType('NmePowershell.Models.NotificationConditionUpdate')]
    [CmdletBinding(PositionalBinding=$false)]
    Param(

        [Parameter()]
        [string[]]
        $ExclusionKeywords,
        [Parameter()]
        [string]
        $Name,
        [Parameter()]
        [NmePowershell.Models.INotificationConditionRunByUser[]]
        $RunByUsers,
        [Parameter()]
        [NmePowershell.PSArgumentCompleterAttribute("Pending", "Running", "Completed", "Failed", "Cancelled")]
        [string[]]
        $Statuses,
        [Parameter()]
        [NmePowershell.Models.INotificationConditionTarget[]]
        $Targets,
        [Parameter()]
        [string[]]
        $Tasks
    )

    process {
        $Object = [NmePowershell.Models.NotificationConditionUpdate]::New()

        if ($PSBoundParameters.ContainsKey('ExclusionKeywords')) {
            $Object.ExclusionKeywords = $ExclusionKeywords
        }
        if ($PSBoundParameters.ContainsKey('Name')) {
            $Object.Name = $Name
        }
        if ($PSBoundParameters.ContainsKey('RunByUsers')) {
            $Object.RunByUsers = $RunByUsers
        }
        if ($PSBoundParameters.ContainsKey('Statuses')) {
            $Object.Statuses = $Statuses
        }
        if ($PSBoundParameters.ContainsKey('Targets')) {
            $Object.Targets = $Targets
        }
        if ($PSBoundParameters.ContainsKey('Tasks')) {
            $Object.Tasks = $Tasks
        }
        return $Object
    }
}

