
# ----------------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.10.8, generator: @autorest/powershell@4.0.752)
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# ----------------------------------------------------------------------------------

<#
.Synopsis
Create an in-memory object for HostChange.
.Description
Create an in-memory object for HostChange.

.Outputs
NmePowershell.Models.HostChange

#>
function New-NmeHostChangeModel {
    [NmePowershell.ModelCmdletAttribute()]
    [OutputType('NmePowershell.Models.HostChange')]
    [CmdletBinding(PositionalBinding=$false)]
    Param(

        [Parameter(Mandatory)]
        [int]
        $HostChangeCount,
        [Parameter(Mandatory)]
        [float]
        $Value
    )

    process {
        $Object = [NmePowershell.Models.HostChange]::New()

        if ($PSBoundParameters.ContainsKey('HostChangeCount')) {
            $Object.HostChangeCount = $HostChangeCount
        }
        if ($PSBoundParameters.ContainsKey('Value')) {
            $Object.Value = $Value
        }
        return $Object
    }
}

