
# ----------------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.10.8, generator: @autorest/powershell@4.0.752)
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# ----------------------------------------------------------------------------------

<#
.Synopsis
Create an in-memory object for SecureVariableUpdate.
.Description
Create an in-memory object for SecureVariableUpdate.

.Outputs
NmePowershell.Models.SecureVariableUpdate

#>
function New-NmeSecureVariableUpdateModel {
    [NmePowershell.ModelCmdletAttribute()]
    [OutputType('NmePowershell.Models.SecureVariableUpdate')]
    [CmdletBinding(PositionalBinding=$false)]
    Param(

        [Parameter()]
        [bool]
        $AssignmentRequired,
        [Parameter(Mandatory)]
        [string]
        $Name,
        [Parameter()]
        [int[]]
        $ScriptedActions,
        [Parameter()]
        [bool]
        $ShellAppAccessible,
        [Parameter()]
        [string]
        $Value
    )

    process {
        $Object = [NmePowershell.Models.SecureVariableUpdate]::New()

        if ($PSBoundParameters.ContainsKey('AssignmentRequired')) {
            $Object.AssignmentRequired = $AssignmentRequired
        }
        if ($PSBoundParameters.ContainsKey('Name')) {
            $Object.Name = $Name
        }
        if ($PSBoundParameters.ContainsKey('ScriptedActions')) {
            $Object.ScriptedActions = $ScriptedActions
        }
        if ($PSBoundParameters.ContainsKey('ShellAppAccessible')) {
            $Object.ShellAppAccessible = $ShellAppAccessible
        }
        if ($PSBoundParameters.ContainsKey('Value')) {
            $Object.Value = $Value
        }
        return $Object
    }
}

