
# ----------------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.10.8, generator: @autorest/powershell@4.0.752)
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# ----------------------------------------------------------------------------------

<#
.Synopsis
Create an in-memory object for NotificationActionDeliveryUpdate.
.Description
Create an in-memory object for NotificationActionDeliveryUpdate.

.Outputs
NmePowershell.Models.NotificationActionDeliveryUpdate

#>
function New-NmeNotificationActionDeliveryUpdateModel {
    [NmePowershell.ModelCmdletAttribute()]
    [OutputType('NmePowershell.Models.NotificationActionDeliveryUpdate')]
    [CmdletBinding(PositionalBinding=$false)]
    Param(

        [Parameter()]
        [NmePowershell.PSArgumentCompleterAttribute("None", "EntraIdManager")]
        [string[]]
        $EmailBuiltInRecipients,
        [Parameter()]
        [bool]
        $EmailEnable,
        [Parameter()]
        [int]
        $EmailMailboxId,
        [Parameter()]
        [string[]]
        $EmailSendTo,
        [Parameter()]
        [bool]
        $WebhookEnable,
        [Parameter()]
        [int]
        $WebhookId
    )

    process {
        $Object = [NmePowershell.Models.NotificationActionDeliveryUpdate]::New()

        if ($PSBoundParameters.ContainsKey('EmailBuiltInRecipients')) {
            $Object.EmailBuiltInRecipients = $EmailBuiltInRecipients
        }
        if ($PSBoundParameters.ContainsKey('EmailEnable')) {
            $Object.EmailEnable = $EmailEnable
        }
        if ($PSBoundParameters.ContainsKey('EmailMailboxId')) {
            $Object.EmailMailboxId = $EmailMailboxId
        }
        if ($PSBoundParameters.ContainsKey('EmailSendTo')) {
            $Object.EmailSendTo = $EmailSendTo
        }
        if ($PSBoundParameters.ContainsKey('WebhookEnable')) {
            $Object.WebhookEnable = $WebhookEnable
        }
        if ($PSBoundParameters.ContainsKey('WebhookId')) {
            $Object.WebhookId = $WebhookId
        }
        return $Object
    }
}

