
# ----------------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.10.8, generator: @autorest/powershell@4.0.752)
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# ----------------------------------------------------------------------------------

<#
.Synopsis
Create an in-memory object for AzureFilesPreStageConfigUpdate.
.Description
Create an in-memory object for AzureFilesPreStageConfigUpdate.

.Outputs
NmePowershell.Models.AzureFilesPreStageConfigUpdate

#>
function New-NmeAzureFilesPreStageConfigUpdateModel {
    [NmePowershell.ModelCmdletAttribute()]
    [OutputType('NmePowershell.Models.AzureFilesPreStageConfigUpdate')]
    [CmdletBinding(PositionalBinding=$false)]
    Param(

        [Parameter()]
        [bool]
        $IsEnabled,
        [Parameter()]
        [int]
        $QuotaBuffer,
        [Parameter()]
        [string]
        $TimezoneId,
        [Parameter()]
        [NmePowershell.PSArgumentCompleterAttribute("0", "1", "2", "3", "4", "5", "6")]
        [int[]]
        $WorkDays
    )

    process {
        $Object = [NmePowershell.Models.AzureFilesPreStageConfigUpdate]::New()

        if ($PSBoundParameters.ContainsKey('IsEnabled')) {
            $Object.IsEnabled = $IsEnabled
        }
        if ($PSBoundParameters.ContainsKey('QuotaBuffer')) {
            $Object.QuotaBuffer = $QuotaBuffer
        }
        if ($PSBoundParameters.ContainsKey('TimezoneId')) {
            $Object.TimezoneId = $TimezoneId
        }
        if ($PSBoundParameters.ContainsKey('WorkDays')) {
            $Object.WorkDays = $WorkDays
        }
        return $Object
    }
}

