
# ----------------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.10.8, generator: @autorest/powershell@4.0.752)
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# ----------------------------------------------------------------------------------

<#
.Synopsis
Create an in-memory object for ConsoleConnectRegionEnable.
.Description
Create an in-memory object for ConsoleConnectRegionEnable.

.Outputs
NmePowershell.Models.ConsoleConnectRegionEnable

#>
function New-NmeConsoleConnectRegionEnableModel {
    [NmePowershell.ModelCmdletAttribute()]
    [OutputType('NmePowershell.Models.ConsoleConnectRegionEnable')]
    [CmdletBinding(PositionalBinding=$false)]
    Param(

        [Parameter()]
        [bool]
        $AllowUninstall
    )

    process {
        $Object = [NmePowershell.Models.ConsoleConnectRegionEnable]::New()

        if ($PSBoundParameters.ContainsKey('AllowUninstall')) {
            $Object.AllowUninstall = $AllowUninstall
        }
        return $Object
    }
}

