
# ----------------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.10.8, generator: @autorest/powershell@4.0.752)
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# ----------------------------------------------------------------------------------

<#
.Synopsis
Create an in-memory object for ReimageMessaging.
.Description
Create an in-memory object for ReimageMessaging.

.Outputs
NmePowershell.Models.ReimageMessaging

#>
function New-NmeReimageMessagingModel {
    [NmePowershell.ModelCmdletAttribute()]
    [OutputType('NmePowershell.Models.ReimageMessaging')]
    [CmdletBinding(PositionalBinding=$false)]
    Param(

        [Parameter()]
        [bool]
        $DeactivateBeforeOperation,
        [Parameter()]
        [int]
        $DelayMinutes,
        [Parameter()]
        [NmePowershell.PSArgumentCompleterAttribute("Force", "Wait")]
        [string]
        $LogOffAggressiveness,
        [Parameter()]
        [string]
        $Message,
        [Parameter()]
        [int]
        $TimeoutInDays
    )

    process {
        $Object = [NmePowershell.Models.ReimageMessaging]::New()

        if ($PSBoundParameters.ContainsKey('DeactivateBeforeOperation')) {
            $Object.DeactivateBeforeOperation = $DeactivateBeforeOperation
        }
        if ($PSBoundParameters.ContainsKey('DelayMinutes')) {
            $Object.DelayMinutes = $DelayMinutes
        }
        if ($PSBoundParameters.ContainsKey('LogOffAggressiveness')) {
            $Object.LogOffAggressiveness = $LogOffAggressiveness
        }
        if ($PSBoundParameters.ContainsKey('Message')) {
            $Object.Message = $Message
        }
        if ($PSBoundParameters.ContainsKey('TimeoutInDays')) {
            $Object.TimeoutInDays = $TimeoutInDays
        }
        return $Object
    }
}

