
# ----------------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.10.8, generator: @autorest/powershell@4.0.752)
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# ----------------------------------------------------------------------------------

<#
.Synopsis
Create an in-memory object for FsLogixOptionalRegistrySettings.
.Description
Create an in-memory object for FsLogixOptionalRegistrySettings.

.Outputs
NmePowershell.Models.FsLogixOptionalRegistrySettings

#>
function New-NmeFsLogixOptionalRegistrySettingsModel {
    [NmePowershell.ModelCmdletAttribute()]
    [OutputType('NmePowershell.Models.FsLogixOptionalRegistrySettings')]
    [CmdletBinding(PositionalBinding=$false)]
    Param(

        [Parameter()]
        [string]
        $RegistryOptions,
        [Parameter(Mandatory)]
        [NmePowershell.PSArgumentCompleterAttribute("None", "Apply")]
        [string]
        $RegistryOptionsMode
    )

    process {
        $Object = [NmePowershell.Models.FsLogixOptionalRegistrySettings]::New()

        if ($PSBoundParameters.ContainsKey('RegistryOptions')) {
            $Object.RegistryOptions = $RegistryOptions
        }
        if ($PSBoundParameters.ContainsKey('RegistryOptionsMode')) {
            $Object.RegistryOptionsMode = $RegistryOptionsMode
        }
        return $Object
    }
}

