
# ----------------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.10.8, generator: @autorest/powershell@4.0.752)
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# ----------------------------------------------------------------------------------

<#
.Synopsis
Create an in-memory object for NotificationConditionTarget.
.Description
Create an in-memory object for NotificationConditionTarget.

.Outputs
NmePowershell.Models.NotificationConditionTarget

#>
function New-NmeNotificationConditionTargetModel {
    [NmePowershell.ModelCmdletAttribute()]
    [OutputType('NmePowershell.Models.NotificationConditionTarget')]
    [CmdletBinding(PositionalBinding=$false)]
    Param(

        [Parameter(Mandatory)]
        [NmePowershell.PSArgumentCompleterAttribute("Workspace", "HostPool", "WorkspaceAny", "HostPoolAny")]
        [string]
        $Scope,
        [Parameter()]
        [string]
        $Value
    )

    process {
        $Object = [NmePowershell.Models.NotificationConditionTarget]::New()

        if ($PSBoundParameters.ContainsKey('Scope')) {
            $Object.Scope = $Scope
        }
        if ($PSBoundParameters.ContainsKey('Value')) {
            $Object.Value = $Value
        }
        return $Object
    }
}

