
# ----------------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.10.8, generator: @autorest/powershell@4.0.752)
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# ----------------------------------------------------------------------------------

<#
.Synopsis
Create an in-memory object for WorkingHours.
.Description
Create an in-memory object for WorkingHours.

.Outputs
NmePowershell.Models.WorkingHours

#>
function New-NmeWorkingHoursModel {
    [NmePowershell.ModelCmdletAttribute()]
    [OutputType('NmePowershell.Models.WorkingHours')]
    [CmdletBinding(PositionalBinding=$false)]
    Param(

        [Parameter(Mandatory)]
        [NmePowershell.PSArgumentCompleterAttribute("0", "1", "2", "3", "4", "5", "6")]
        [int[]]
        $Days,
        [Parameter(Mandatory)]
        [int]
        $TimeIntervalDuration,
        [Parameter(Mandatory)]
        [int]
        $TimeIntervalHour,
        [Parameter()]
        [int]
        $TimeIntervalMinutes
    )

    process {
        $Object = [NmePowershell.Models.WorkingHours]::New()

        if ($PSBoundParameters.ContainsKey('Days')) {
            $Object.Days = $Days
        }
        if ($PSBoundParameters.ContainsKey('TimeIntervalDuration')) {
            $Object.TimeIntervalDuration = $TimeIntervalDuration
        }
        if ($PSBoundParameters.ContainsKey('TimeIntervalHour')) {
            $Object.TimeIntervalHour = $TimeIntervalHour
        }
        if ($PSBoundParameters.ContainsKey('TimeIntervalMinutes')) {
            $Object.TimeIntervalMinutes = $TimeIntervalMinutes
        }
        return $Object
    }
}

