
# ----------------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.10.8, generator: @autorest/powershell@4.0.752)
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# ----------------------------------------------------------------------------------

<#
.Synopsis
Create an in-memory object for HostPoolControlUpMaintenanceWindow.
.Description
Create an in-memory object for HostPoolControlUpMaintenanceWindow.

.Outputs
NmePowershell.Models.HostPoolControlUpMaintenanceWindow

#>
function New-NmeHostPoolControlUpMaintenanceWindowModel {
    [NmePowershell.ModelCmdletAttribute()]
    [OutputType('NmePowershell.Models.HostPoolControlUpMaintenanceWindow')]
    [CmdletBinding(PositionalBinding=$false)]
    Param(

        [Parameter()]
        [NmePowershell.PSArgumentCompleterAttribute("0", "1", "2", "3", "4", "5", "6")]
        [int[]]
        $Days,
        [Parameter()]
        [int]
        $DurationMinutes,
        [Parameter(Mandatory)]
        [bool]
        $Enabled,
        [Parameter()]
        [int]
        $StartHour,
        [Parameter()]
        [int]
        $StartMinutes,
        [Parameter()]
        [string]
        $TimezoneId
    )

    process {
        $Object = [NmePowershell.Models.HostPoolControlUpMaintenanceWindow]::New()

        if ($PSBoundParameters.ContainsKey('Days')) {
            $Object.Days = $Days
        }
        if ($PSBoundParameters.ContainsKey('DurationMinutes')) {
            $Object.DurationMinutes = $DurationMinutes
        }
        if ($PSBoundParameters.ContainsKey('Enabled')) {
            $Object.Enabled = $Enabled
        }
        if ($PSBoundParameters.ContainsKey('StartHour')) {
            $Object.StartHour = $StartHour
        }
        if ($PSBoundParameters.ContainsKey('StartMinutes')) {
            $Object.StartMinutes = $StartMinutes
        }
        if ($PSBoundParameters.ContainsKey('TimezoneId')) {
            $Object.TimezoneId = $TimezoneId
        }
        return $Object
    }
}

