
# ----------------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.10.8, generator: @autorest/powershell@4.0.752)
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# ----------------------------------------------------------------------------------

<#
.Synopsis
Create an in-memory object for HostUsageConfiguration.
.Description
Create an in-memory object for HostUsageConfiguration.

.Outputs
NmePowershell.Models.HostUsageConfiguration

#>
function New-NmeHostUsageConfigurationModel {
    [NmePowershell.ModelCmdletAttribute()]
    [OutputType('NmePowershell.Models.HostUsageConfiguration')]
    [CmdletBinding(PositionalBinding=$false)]
    Param(

        [Parameter(Mandatory)]
        [int]
        $ScaleInAverageTimeRangeInMinutes,
        [Parameter(Mandatory)]
        [int]
        $ScaleInHostChangeCount,
        [Parameter(Mandatory)]
        [float]
        $ScaleInValue,
        [Parameter(Mandatory)]
        [int]
        $ScaleOutAverageTimeRangeInMinutes,
        [Parameter(Mandatory)]
        [int]
        $ScaleOutHostChangeCount,
        [Parameter(Mandatory)]
        [float]
        $ScaleOutValue
    )

    process {
        $Object = [NmePowershell.Models.HostUsageConfiguration]::New()

        if ($PSBoundParameters.ContainsKey('ScaleInAverageTimeRangeInMinutes')) {
            $Object.ScaleInAverageTimeRangeInMinutes = $ScaleInAverageTimeRangeInMinutes
        }
        if ($PSBoundParameters.ContainsKey('ScaleInHostChangeCount')) {
            $Object.ScaleInHostChangeCount = $ScaleInHostChangeCount
        }
        if ($PSBoundParameters.ContainsKey('ScaleInValue')) {
            $Object.ScaleInValue = $ScaleInValue
        }
        if ($PSBoundParameters.ContainsKey('ScaleOutAverageTimeRangeInMinutes')) {
            $Object.ScaleOutAverageTimeRangeInMinutes = $ScaleOutAverageTimeRangeInMinutes
        }
        if ($PSBoundParameters.ContainsKey('ScaleOutHostChangeCount')) {
            $Object.ScaleOutHostChangeCount = $ScaleOutHostChangeCount
        }
        if ($PSBoundParameters.ContainsKey('ScaleOutValue')) {
            $Object.ScaleOutValue = $ScaleOutValue
        }
        return $Object
    }
}

