
# ----------------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.10.8, generator: @autorest/powershell@4.0.752)
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# ----------------------------------------------------------------------------------

<#
.Synopsis
Create an in-memory object for HostPoolAssignment.
.Description
Create an in-memory object for HostPoolAssignment.

.Outputs
NmePowershell.Models.HostPoolAssignment

#>
function New-NmeHostPoolAssignmentModel {
    [NmePowershell.ModelCmdletAttribute()]
    [OutputType('NmePowershell.Models.HostPoolAssignment')]
    [CmdletBinding(PositionalBinding=$false)]
    Param(

        [Parameter(Mandatory)]
        [string]
        $ObjectId,
        [Parameter(Mandatory)]
        [NmePowershell.PSArgumentCompleterAttribute("User", "Group")]
        [string]
        $ObjectType
    )

    process {
        $Object = [NmePowershell.Models.HostPoolAssignment]::New()

        if ($PSBoundParameters.ContainsKey('ObjectId')) {
            $Object.ObjectId = $ObjectId
        }
        if ($PSBoundParameters.ContainsKey('ObjectType')) {
            $Object.ObjectType = $ObjectType
        }
        return $Object
    }
}

