
# ----------------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.10.8, generator: @autorest/powershell@4.0.752)
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# ----------------------------------------------------------------------------------

<#
.Synopsis
Create an in-memory object for AnyUamPolicyActionCreate.
.Description
Create an in-memory object for AnyUamPolicyActionCreate.

.Outputs
NmePowershell.Models.AnyUamPolicyActionCreate

#>
function New-NmeAnyUamPolicyActionCreateModel {
    [NmePowershell.ModelCmdletAttribute()]
    [OutputType('NmePowershell.Models.AnyUamPolicyActionCreate')]
    [CmdletBinding(PositionalBinding=$false)]
    Param(

        [Parameter()]
        [string]
        $ExternalId,
        [Parameter()]
        [int]
        $GroupId,
        [Parameter()]
        [string]
        $GroupName,
        [Parameter()]
        [string]
        $Name,
        [Parameter()]
        [bool]
        $Reboot,
        [Parameter()]
        [int]
        $RepoId,
        [Parameter(Mandatory)]
        [NmePowershell.PSArgumentCompleterAttribute("Install", "Uninstall", "InstallGroup", "UninstallGroup")]
        [string]
        $Type,
        [Parameter()]
        [string]
        $Version
    )

    process {
        $Object = [NmePowershell.Models.AnyUamPolicyActionCreate]::New()

        if ($PSBoundParameters.ContainsKey('ExternalId')) {
            $Object.ExternalId = $ExternalId
        }
        if ($PSBoundParameters.ContainsKey('GroupId')) {
            $Object.GroupId = $GroupId
        }
        if ($PSBoundParameters.ContainsKey('GroupName')) {
            $Object.GroupName = $GroupName
        }
        if ($PSBoundParameters.ContainsKey('Name')) {
            $Object.Name = $Name
        }
        if ($PSBoundParameters.ContainsKey('Reboot')) {
            $Object.Reboot = $Reboot
        }
        if ($PSBoundParameters.ContainsKey('RepoId')) {
            $Object.RepoId = $RepoId
        }
        if ($PSBoundParameters.ContainsKey('Type')) {
            $Object.Type = $Type
        }
        if ($PSBoundParameters.ContainsKey('Version')) {
            $Object.Version = $Version
        }
        return $Object
    }
}

