
# ----------------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.10.8, generator: @autorest/powershell@4.0.752)
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# ----------------------------------------------------------------------------------

<#
.Synopsis
Create an in-memory object for RunScriptBulkJobWithHostsParams.
.Description
Create an in-memory object for RunScriptBulkJobWithHostsParams.

.Outputs
NmePowershell.Models.RunScriptBulkJobWithHostsParams

#>
function New-NmeRunScriptBulkJobWithHostsParamsModel {
    [NmePowershell.ModelCmdletAttribute()]
    [OutputType('NmePowershell.Models.RunScriptBulkJobWithHostsParams')]
    [CmdletBinding(PositionalBinding=$false)]
    Param(

        [Parameter(Mandatory)]
        [int]
        $CountFailedTaskToStopWork,
        [Parameter()]
        [bool]
        $EnableDrainMode,
        [Parameter(Mandatory)]
        [bool]
        $ExcludeNotRunning,
        [Parameter()]
        [string]
        $Message,
        [Parameter()]
        [int]
        $MinutesBeforeRemove,
        [Parameter(Mandatory)]
        [bool]
        $RestartVms,
        [Parameter()]
        [string[]]
        $SessionHostsToProcessNames,
        [Parameter(Mandatory)]
        [int]
        $TaskParallelism
    )

    process {
        $Object = [NmePowershell.Models.RunScriptBulkJobWithHostsParams]::New()

        if ($PSBoundParameters.ContainsKey('CountFailedTaskToStopWork')) {
            $Object.CountFailedTaskToStopWork = $CountFailedTaskToStopWork
        }
        if ($PSBoundParameters.ContainsKey('EnableDrainMode')) {
            $Object.EnableDrainMode = $EnableDrainMode
        }
        if ($PSBoundParameters.ContainsKey('ExcludeNotRunning')) {
            $Object.ExcludeNotRunning = $ExcludeNotRunning
        }
        if ($PSBoundParameters.ContainsKey('Message')) {
            $Object.Message = $Message
        }
        if ($PSBoundParameters.ContainsKey('MinutesBeforeRemove')) {
            $Object.MinutesBeforeRemove = $MinutesBeforeRemove
        }
        if ($PSBoundParameters.ContainsKey('RestartVms')) {
            $Object.RestartVms = $RestartVms
        }
        if ($PSBoundParameters.ContainsKey('SessionHostsToProcessNames')) {
            $Object.SessionHostsToProcessNames = $SessionHostsToProcessNames
        }
        if ($PSBoundParameters.ContainsKey('TaskParallelism')) {
            $Object.TaskParallelism = $TaskParallelism
        }
        return $Object
    }
}

