
# ----------------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.10.8, generator: @autorest/powershell@4.0.752)
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# ----------------------------------------------------------------------------------

<#
.Synopsis
Create an in-memory object for HostPoolRdpUpdate.
.Description
Create an in-memory object for HostPoolRdpUpdate.

.Outputs
NmePowershell.Models.HostPoolRdpUpdate

#>
function New-NmeHostPoolRdpUpdateModel {
    [NmePowershell.ModelCmdletAttribute()]
    [OutputType('NmePowershell.Models.HostPoolRdpUpdate')]
    [CmdletBinding(PositionalBinding=$false)]
    Param(

        [Parameter()]
        [string]
        $ConfigurationName,
        [Parameter()]
        [string]
        $RdpProperties,
        [Parameter()]
        [NmePowershell.PSArgumentCompleterAttribute("Unknown", "Default", "Disabled", "Enabled")]
        [string]
        $ShortPathDirectUdp,
        [Parameter()]
        [NmePowershell.PSArgumentCompleterAttribute("Unknown", "Default", "Disabled", "Enabled")]
        [string]
        $ShortPathManagedPrivateUdp,
        [Parameter()]
        [NmePowershell.PSArgumentCompleterAttribute("Unknown", "Default", "Disabled", "Enabled")]
        [string]
        $ShortPathPublicUdp,
        [Parameter()]
        [NmePowershell.PSArgumentCompleterAttribute("Unknown", "Default", "Disabled", "Enabled")]
        [string]
        $ShortPathRelayUdp
    )

    process {
        $Object = [NmePowershell.Models.HostPoolRdpUpdate]::New()

        if ($PSBoundParameters.ContainsKey('ConfigurationName')) {
            $Object.ConfigurationName = $ConfigurationName
        }
        if ($PSBoundParameters.ContainsKey('RdpProperties')) {
            $Object.RdpProperties = $RdpProperties
        }
        if ($PSBoundParameters.ContainsKey('ShortPathDirectUdp')) {
            $Object.ShortPathDirectUdp = $ShortPathDirectUdp
        }
        if ($PSBoundParameters.ContainsKey('ShortPathManagedPrivateUdp')) {
            $Object.ShortPathManagedPrivateUdp = $ShortPathManagedPrivateUdp
        }
        if ($PSBoundParameters.ContainsKey('ShortPathPublicUdp')) {
            $Object.ShortPathPublicUdp = $ShortPathPublicUdp
        }
        if ($PSBoundParameters.ContainsKey('ShortPathRelayUdp')) {
            $Object.ShortPathRelayUdp = $ShortPathRelayUdp
        }
        return $Object
    }
}

