
# ----------------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.10.8, generator: @autorest/powershell@4.0.752)
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# ----------------------------------------------------------------------------------

<#
.Synopsis
Create an in-memory object for PortalNotificationUpdate.
.Description
Create an in-memory object for PortalNotificationUpdate.

.Outputs
NmePowershell.Models.PortalNotificationUpdate

#>
function New-NmePortalNotificationUpdateModel {
    [NmePowershell.ModelCmdletAttribute()]
    [OutputType('NmePowershell.Models.PortalNotificationUpdate')]
    [CmdletBinding(PositionalBinding=$false)]
    Param(

        [Parameter(Mandatory)]
        [string]
        $HtmlText,
        [Parameter()]
        [System.DateTime]
        $PeriodEndDate,
        [Parameter()]
        [System.DateTime]
        $PeriodStartDate,
        [Parameter()]
        [string]
        $PeriodTimeZoneId
    )

    process {
        $Object = [NmePowershell.Models.PortalNotificationUpdate]::New()

        if ($PSBoundParameters.ContainsKey('HtmlText')) {
            $Object.HtmlText = $HtmlText
        }
        if ($PSBoundParameters.ContainsKey('PeriodEndDate')) {
            $Object.PeriodEndDate = $PeriodEndDate
        }
        if ($PSBoundParameters.ContainsKey('PeriodStartDate')) {
            $Object.PeriodStartDate = $PeriodStartDate
        }
        if ($PSBoundParameters.ContainsKey('PeriodTimeZoneId')) {
            $Object.PeriodTimeZoneId = $PeriodTimeZoneId
        }
        return $Object
    }
}

