
# ----------------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.10.8, generator: @autorest/powershell@4.0.752)
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# ----------------------------------------------------------------------------------

<#
.Synopsis
Create an in-memory object for PowerStateCommandExtensions.
.Description
Create an in-memory object for PowerStateCommandExtensions.

.Outputs
NmePowershell.Models.PowerStateCommandExtensions

#>
function New-NmePowerStateCommandExtensionsModel {
    [NmePowershell.ModelCmdletAttribute()]
    [OutputType('NmePowershell.Models.PowerStateCommandExtensions')]
    [CmdletBinding(PositionalBinding=$false)]
    Param(

        [Parameter(Mandatory)]
        [bool]
        $Hibernation
    )

    process {
        $Object = [NmePowershell.Models.PowerStateCommandExtensions]::New()

        if ($PSBoundParameters.ContainsKey('Hibernation')) {
            $Object.Hibernation = $Hibernation
        }
        return $Object
    }
}

