
# ----------------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.10.8, generator: @autorest/powershell@4.0.752)
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# ----------------------------------------------------------------------------------

<#
.Synopsis
Create an in-memory object for GalleryImageConfiguration.
.Description
Create an in-memory object for GalleryImageConfiguration.

.Outputs
NmePowershell.Models.GalleryImageConfiguration

#>
function New-NmeGalleryImageConfigurationModel {
    [NmePowershell.ModelCmdletAttribute()]
    [OutputType('NmePowershell.Models.GalleryImageConfiguration')]
    [CmdletBinding(PositionalBinding=$false)]
    Param(

        [Parameter(Mandatory)]
        [string]
        $GalleryId,
        [Parameter(Mandatory)]
        [bool]
        $HibernationSupported,
        [Parameter(Mandatory)]
        [NmePowershell.PSArgumentCompleterAttribute("None", "TrustedLaunch", "Confidential", "TrustedLaunchSupported", "ConfidentialSupported", "TrustedLaunchAndConfidentialSupported")]
        [string]
        $ImageSecurityType,
        [Parameter(Mandatory)]
        [NmePowershell.PSArgumentCompleterAttribute("Generalized", "Specialized")]
        [string]
        $OSState,
        [Parameter()]
        [int]
        $ReplicaCount,
        [Parameter(Mandatory)]
        [bool]
        $SetInactive,
        [Parameter(Mandatory)]
        [string[]]
        $TargetRegions,
        [Parameter(Mandatory)]
        [NmePowershell.PSArgumentCompleterAttribute("Major", "Minor", "Revision")]
        [string]
        $VersionIncrementType
    )

    process {
        $Object = [NmePowershell.Models.GalleryImageConfiguration]::New()

        if ($PSBoundParameters.ContainsKey('GalleryId')) {
            $Object.GalleryId = $GalleryId
        }
        if ($PSBoundParameters.ContainsKey('HibernationSupported')) {
            $Object.HibernationSupported = $HibernationSupported
        }
        if ($PSBoundParameters.ContainsKey('ImageSecurityType')) {
            $Object.ImageSecurityType = $ImageSecurityType
        }
        if ($PSBoundParameters.ContainsKey('OSState')) {
            $Object.OSState = $OSState
        }
        if ($PSBoundParameters.ContainsKey('ReplicaCount')) {
            $Object.ReplicaCount = $ReplicaCount
        }
        if ($PSBoundParameters.ContainsKey('SetInactive')) {
            $Object.SetInactive = $SetInactive
        }
        if ($PSBoundParameters.ContainsKey('TargetRegions')) {
            $Object.TargetRegions = $TargetRegions
        }
        if ($PSBoundParameters.ContainsKey('VersionIncrementType')) {
            $Object.VersionIncrementType = $VersionIncrementType
        }
        return $Object
    }
}

