
# ----------------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.10.8, generator: @autorest/powershell@4.0.752)
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# ----------------------------------------------------------------------------------

<#
.Synopsis
Create an in-memory object for NotificationActionConditionsUpdate.
.Description
Create an in-memory object for NotificationActionConditionsUpdate.

.Outputs
NmePowershell.Models.NotificationActionConditionsUpdate

#>
function New-NmeNotificationActionConditionsUpdateModel {
    [NmePowershell.ModelCmdletAttribute()]
    [OutputType('NmePowershell.Models.NotificationActionConditionsUpdate')]
    [CmdletBinding(PositionalBinding=$false)]
    Param(

        [Parameter()]
        [int[]]
        $NerdioConditionIds
    )

    process {
        $Object = [NmePowershell.Models.NotificationActionConditionsUpdate]::New()

        if ($PSBoundParameters.ContainsKey('NerdioConditionIds')) {
            $Object.NerdioConditionIds = $NerdioConditionIds
        }
        return $Object
    }
}

