
# ----------------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.10.8, generator: @autorest/powershell@4.0.752)
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# ----------------------------------------------------------------------------------

<#
.Synopsis
Create an in-memory object for FsLogixRegistryUpdate.
.Description
Create an in-memory object for FsLogixRegistryUpdate.

.Outputs
NmePowershell.Models.FsLogixRegistryUpdate

#>
function New-NmeFsLogixRegistryUpdateModel {
    [NmePowershell.ModelCmdletAttribute()]
    [OutputType('NmePowershell.Models.FsLogixRegistryUpdate')]
    [CmdletBinding(PositionalBinding=$false)]
    Param(

        [Parameter()]
        [string[]]
        $Locations,
        [Parameter()]
        [string]
        $Options
    )

    process {
        $Object = [NmePowershell.Models.FsLogixRegistryUpdate]::New()

        if ($PSBoundParameters.ContainsKey('Locations')) {
            $Object.Locations = $Locations
        }
        if ($PSBoundParameters.ContainsKey('Options')) {
            $Object.Options = $Options
        }
        return $Object
    }
}

