
# ----------------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.10.8, generator: @autorest/powershell@4.0.752)
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# ----------------------------------------------------------------------------------

<#
.Synopsis
Create an in-memory object for ShellAppUpdate.
.Description
Create an in-memory object for ShellAppUpdate.

.Outputs
NmePowershell.Models.ShellAppUpdate

#>
function New-NmeShellAppUpdateModel {
    [NmePowershell.ModelCmdletAttribute()]
    [OutputType('NmePowershell.Models.ShellAppUpdate')]
    [CmdletBinding(PositionalBinding=$false)]
    Param(

        [Parameter()]
        [string]
        $Description,
        [Parameter()]
        [string]
        $DetectScript,
        [Parameter()]
        [bool]
        $FileUnzip,
        [Parameter()]
        [string]
        $InstallScript,
        [Parameter()]
        [bool]
        $IsPublic,
        [Parameter()]
        [string]
        $Name,
        [Parameter()]
        [string]
        $Publisher,
        [Parameter()]
        [string]
        $UninstallScript
    )

    process {
        $Object = [NmePowershell.Models.ShellAppUpdate]::New()

        if ($PSBoundParameters.ContainsKey('Description')) {
            $Object.Description = $Description
        }
        if ($PSBoundParameters.ContainsKey('DetectScript')) {
            $Object.DetectScript = $DetectScript
        }
        if ($PSBoundParameters.ContainsKey('FileUnzip')) {
            $Object.FileUnzip = $FileUnzip
        }
        if ($PSBoundParameters.ContainsKey('InstallScript')) {
            $Object.InstallScript = $InstallScript
        }
        if ($PSBoundParameters.ContainsKey('IsPublic')) {
            $Object.IsPublic = $IsPublic
        }
        if ($PSBoundParameters.ContainsKey('Name')) {
            $Object.Name = $Name
        }
        if ($PSBoundParameters.ContainsKey('Publisher')) {
            $Object.Publisher = $Publisher
        }
        if ($PSBoundParameters.ContainsKey('UninstallScript')) {
            $Object.UninstallScript = $UninstallScript
        }
        return $Object
    }
}

