
# ----------------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.10.8, generator: @autorest/powershell@4.0.752)
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# ----------------------------------------------------------------------------------

<#
.Synopsis
Create an in-memory object for VmObjectId.
.Description
Create an in-memory object for VmObjectId.

.Outputs
NmePowershell.Models.VmObjectId

#>
function New-NmeVmObjectIdModel {
    [NmePowershell.ModelCmdletAttribute()]
    [OutputType('NmePowershell.Models.VmObjectId')]
    [CmdletBinding(PositionalBinding=$false)]
    Param(

        [Parameter(Mandatory)]
        [bool]
        $AddSuffix,
        [Parameter(Mandatory)]
        [string]
        $Name,
        [Parameter(Mandatory)]
        [string]
        $ResourceGroup,
        [Parameter(Mandatory)]
        [string]
        $SubscriptionId
    )

    process {
        $Object = [NmePowershell.Models.VmObjectId]::New()

        if ($PSBoundParameters.ContainsKey('AddSuffix')) {
            $Object.AddSuffix = $AddSuffix
        }
        if ($PSBoundParameters.ContainsKey('Name')) {
            $Object.Name = $Name
        }
        if ($PSBoundParameters.ContainsKey('ResourceGroup')) {
            $Object.ResourceGroup = $ResourceGroup
        }
        if ($PSBoundParameters.ContainsKey('SubscriptionId')) {
            $Object.SubscriptionId = $SubscriptionId
        }
        return $Object
    }
}

