
# ----------------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.10.8, generator: @autorest/powershell@4.0.752)
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# ----------------------------------------------------------------------------------

<#
.Synopsis
Create an in-memory object for FsLogixInstaller.
.Description
Create an in-memory object for FsLogixInstaller.

.Outputs
NmePowershell.Models.FsLogixInstaller

#>
function New-NmeFsLogixInstallerModel {
    [NmePowershell.ModelCmdletAttribute()]
    [OutputType('NmePowershell.Models.FsLogixInstaller')]
    [CmdletBinding(PositionalBinding=$false)]
    Param(

        [Parameter(Mandatory)]
        [bool]
        $ForceUpdate,
        [Parameter(Mandatory)]
        [string]
        $Version
    )

    process {
        $Object = [NmePowershell.Models.FsLogixInstaller]::New()

        if ($PSBoundParameters.ContainsKey('ForceUpdate')) {
            $Object.ForceUpdate = $ForceUpdate
        }
        if ($PSBoundParameters.ContainsKey('Version')) {
            $Object.Version = $Version
        }
        return $Object
    }
}

