
# ----------------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.10.8, generator: @autorest/powershell@4.0.752)
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# ----------------------------------------------------------------------------------

<#
.Synopsis
Create an in-memory object for AvdAgentMaintenanceWindow.
.Description
Create an in-memory object for AvdAgentMaintenanceWindow.

.Outputs
NmePowershell.Models.AvdAgentMaintenanceWindow

#>
function New-NmeAvdAgentMaintenanceWindowModel {
    [NmePowershell.ModelCmdletAttribute()]
    [OutputType('NmePowershell.Models.AvdAgentMaintenanceWindow')]
    [CmdletBinding(PositionalBinding=$false)]
    Param(

        [Parameter(Mandatory)]
        [NmePowershell.PSArgumentCompleterAttribute("0", "1", "2", "3", "4", "5", "6")]
        [int]
        $DayOfWeek,
        [Parameter(Mandatory)]
        [int]
        $Hour
    )

    process {
        $Object = [NmePowershell.Models.AvdAgentMaintenanceWindow]::New()

        if ($PSBoundParameters.ContainsKey('DayOfWeek')) {
            $Object.DayOfWeek = $DayOfWeek
        }
        if ($PSBoundParameters.ContainsKey('Hour')) {
            $Object.Hour = $Hour
        }
        return $Object
    }
}

