
# ----------------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.10.8, generator: @autorest/powershell@4.0.752)
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# ----------------------------------------------------------------------------------

<#
.Synopsis
Create an in-memory object for AppPolicyOneTimeCreate.
.Description
Create an in-memory object for AppPolicyOneTimeCreate.

.Outputs
NmePowershell.Models.AppPolicyOneTimeCreate

#>
function New-NmeAppPolicyOneTimeCreateModel {
    [NmePowershell.ModelCmdletAttribute()]
    [OutputType('NmePowershell.Models.AppPolicyOneTimeCreate')]
    [CmdletBinding(PositionalBinding=$false)]
    Param(

        [Parameter(Mandatory)]
        [NmePowershell.Models.IAnyAppActionCreate[]]
        $Actions,
        [Parameter(Mandatory)]
        [NmePowershell.PSArgumentCompleterAttribute("Global", "ByPool")]
        [string]
        $ConcurrencyBalancer,
        [Parameter(Mandatory)]
        [int]
        $ConcurrencyMaxJobs,
        [Parameter()]
        [string]
        $Name,
        [Parameter(Mandatory)]
        [NmePowershell.Models.IAnyAppScopeCreate[]]
        $Scopes,
        [Parameter(Mandatory)]
        [NmePowershell.PSArgumentCompleterAttribute("Default", "TaskRunner")]
        [string]
        $ScriptDelivery
    )

    process {
        $Object = [NmePowershell.Models.AppPolicyOneTimeCreate]::New()

        if ($PSBoundParameters.ContainsKey('Actions')) {
            $Object.Actions = $Actions
        }
        if ($PSBoundParameters.ContainsKey('ConcurrencyBalancer')) {
            $Object.ConcurrencyBalancer = $ConcurrencyBalancer
        }
        if ($PSBoundParameters.ContainsKey('ConcurrencyMaxJobs')) {
            $Object.ConcurrencyMaxJobs = $ConcurrencyMaxJobs
        }
        if ($PSBoundParameters.ContainsKey('Name')) {
            $Object.Name = $Name
        }
        if ($PSBoundParameters.ContainsKey('Scopes')) {
            $Object.Scopes = $Scopes
        }
        if ($PSBoundParameters.ContainsKey('ScriptDelivery')) {
            $Object.ScriptDelivery = $ScriptDelivery
        }
        return $Object
    }
}

