
# ----------------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.10.8, generator: @autorest/powershell@4.0.752)
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# ----------------------------------------------------------------------------------

<#
.Synopsis
Create an in-memory object for UserDrivenPreStageHostsConfigurationItem.
.Description
Create an in-memory object for UserDrivenPreStageHostsConfigurationItem.

.Outputs
NmePowershell.Models.UserDrivenPreStageHostsConfigurationItem

#>
function New-NmeUserDrivenPreStageHostsConfigurationItemModel {
    [NmePowershell.ModelCmdletAttribute()]
    [OutputType('NmePowershell.Models.UserDrivenPreStageHostsConfigurationItem')]
    [CmdletBinding(PositionalBinding=$false)]
    Param(

        [Parameter(Mandatory)]
        [NmePowershell.PSArgumentCompleterAttribute("0", "1", "2", "3", "4", "5", "6")]
        [int[]]
        $Days,
        [Parameter(Mandatory)]
        [int]
        $DurationMinutes,
        [Parameter(Mandatory)]
        [string]
        $StartWork
    )

    process {
        $Object = [NmePowershell.Models.UserDrivenPreStageHostsConfigurationItem]::New()

        if ($PSBoundParameters.ContainsKey('Days')) {
            $Object.Days = $Days
        }
        if ($PSBoundParameters.ContainsKey('DurationMinutes')) {
            $Object.DurationMinutes = $DurationMinutes
        }
        if ($PSBoundParameters.ContainsKey('StartWork')) {
            $Object.StartWork = $StartWork
        }
        return $Object
    }
}

