
# ----------------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.10.8, generator: @autorest/powershell@4.0.752)
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# ----------------------------------------------------------------------------------

<#
.Synopsis
Create an in-memory object for AzureFilesScalingConfigUpdate.
.Description
Create an in-memory object for AzureFilesScalingConfigUpdate.

.Outputs
NmePowershell.Models.AzureFilesScalingConfigUpdate

#>
function New-NmeAzureFilesScalingConfigUpdateModel {
    [NmePowershell.ModelCmdletAttribute()]
    [OutputType('NmePowershell.Models.AzureFilesScalingConfigUpdate')]
    [CmdletBinding(PositionalBinding=$false)]
    Param(

        [Parameter()]
        [int]
        $ScaleInBy,
        [Parameter()]
        [int]
        $ScaleInInterval,
        [Parameter()]
        [int]
        $ScaleInLowLatency,
        [Parameter()]
        [int]
        $ScaleOutBy,
        [Parameter()]
        [int]
        $ScaleOutHighLatency,
        [Parameter()]
        [int]
        $ScaleOutInterval,
        [Parameter()]
        [int]
        $TransactionThreshold,
        [Parameter()]
        [NmePowershell.PSArgumentCompleterAttribute("MaxSuccessServerLatency", "AvgSuccessServerLatency")]
        [string]
        $Trigger
    )

    process {
        $Object = [NmePowershell.Models.AzureFilesScalingConfigUpdate]::New()

        if ($PSBoundParameters.ContainsKey('ScaleInBy')) {
            $Object.ScaleInBy = $ScaleInBy
        }
        if ($PSBoundParameters.ContainsKey('ScaleInInterval')) {
            $Object.ScaleInInterval = $ScaleInInterval
        }
        if ($PSBoundParameters.ContainsKey('ScaleInLowLatency')) {
            $Object.ScaleInLowLatency = $ScaleInLowLatency
        }
        if ($PSBoundParameters.ContainsKey('ScaleOutBy')) {
            $Object.ScaleOutBy = $ScaleOutBy
        }
        if ($PSBoundParameters.ContainsKey('ScaleOutHighLatency')) {
            $Object.ScaleOutHighLatency = $ScaleOutHighLatency
        }
        if ($PSBoundParameters.ContainsKey('ScaleOutInterval')) {
            $Object.ScaleOutInterval = $ScaleOutInterval
        }
        if ($PSBoundParameters.ContainsKey('TransactionThreshold')) {
            $Object.TransactionThreshold = $TransactionThreshold
        }
        if ($PSBoundParameters.ContainsKey('Trigger')) {
            $Object.Trigger = $Trigger
        }
        return $Object
    }
}

