
# ----------------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.10.8, generator: @autorest/powershell@4.0.752)
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# ----------------------------------------------------------------------------------

<#
.Synopsis
Create an in-memory object for ArmHostPoolPersonalConfig.
.Description
Create an in-memory object for ArmHostPoolPersonalConfig.

.Outputs
NmePowershell.Models.ArmHostPoolPersonalConfig

#>
function New-NmeArmHostPoolPersonalConfigModel {
    [NmePowershell.ModelCmdletAttribute()]
    [OutputType('NmePowershell.Models.ArmHostPoolPersonalConfig')]
    [CmdletBinding(PositionalBinding=$false)]
    Param(

        [Parameter(Mandatory)]
        [NmePowershell.PSArgumentCompleterAttribute("Automatic", "Direct")]
        [string]
        $AssignmentType,
        [Parameter()]
        [bool]
        $MultiplePersistent
    )

    process {
        $Object = [NmePowershell.Models.ArmHostPoolPersonalConfig]::New()

        if ($PSBoundParameters.ContainsKey('AssignmentType')) {
            $Object.AssignmentType = $AssignmentType
        }
        if ($PSBoundParameters.ContainsKey('MultiplePersistent')) {
            $Object.MultiplePersistent = $MultiplePersistent
        }
        return $Object
    }
}

