
# ----------------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.10.8, generator: @autorest/powershell@4.0.752)
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# ----------------------------------------------------------------------------------

<#
.Synopsis
Create an in-memory object for NetAppFilesAutoscaleConfig.
.Description
Create an in-memory object for NetAppFilesAutoscaleConfig.

#>
function New-NmeNetAppFilesAutoscaleConfigModel {
[OutputType([NmePowershell.Models.NetAppFilesAutoscaleConfig])]
[CmdletBinding(PositionalBinding=$false)]
param(
    [Parameter(Mandatory)]
    [NmePowershell.Category('Body')]
    [System.Double]
    ${BasicMaxSizeBuffer},

    [Parameter(Mandatory)]
    [NmePowershell.Category('Body')]
    [System.Int32]
    ${BasicMaxSizeLimit},

    [Parameter(Mandatory)]
    [NmePowershell.Category('Body')]
    [System.Double]
    ${BasicMinSizeBuffer},

    [Parameter(Mandatory)]
    [NmePowershell.Category('Body')]
    [System.Boolean]
    ${BasicNonGreedyStrategicEnabled},

    [Parameter(Mandatory)]
    [NmePowershell.PSArgumentCompleterAttribute("VolumeOnly", "VolumeAndPool")]
    [NmePowershell.Category('Body')]
    [System.String]
    ${BasicScalingMode},

    [Parameter(Mandatory)]
    [NmePowershell.Category('Body')]
    [System.Boolean]
    ${BasicTriggerLimitExceedingError},

    [Parameter(Mandatory)]
    [NmePowershell.Category('Body')]
    [System.Boolean]
    ${IsEnabled},

    [Parameter(Mandatory)]
    [NmePowershell.Category('Body')]
    [System.Boolean]
    ${PreStageIsEnabled},

    [Parameter(Mandatory)]
    [NmePowershell.Category('Body')]
    [System.Boolean]
    ${ScalingIsEnabled},

    [Parameter(Mandatory)]
    [NmePowershell.PSArgumentCompleterAttribute("Percent", "SizeGb", "SizeTb")]
    [NmePowershell.Category('Body')]
    [System.String]
    ${Unit},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.String]
    ${PreStageTimezoneId},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [NmePowershell.Models.INetAppFilesWorkTimeSet[]]
    # 
    ${PreStageWorkTimeSets},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.Int32]
    ${ScalingScaleInBy},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.Int32]
    ${ScalingScaleInInterval},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.Int32]
    ${ScalingScaleInLowLatency},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.Int32]
    ${ScalingScaleOutBy},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.Int32]
    ${ScalingScaleOutHighLatency},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.Int32]
    ${ScalingScaleOutInterval},

    [Parameter()]
    [NmePowershell.PSArgumentCompleterAttribute("AvgReadLatency", "AvgWriteLatency", "AvgReadOrWriteLatency")]
    [NmePowershell.Category('Body')]
    [System.String]
    ${ScalingTrigger}
)

begin {
    try {
        $outBuffer = $null
        if ($PSBoundParameters.TryGetValue('OutBuffer', [ref]$outBuffer)) {
            $PSBoundParameters['OutBuffer'] = 1
        }
        $parameterSet = $PSCmdlet.ParameterSetName
        
        $testPlayback = $false
        $PSBoundParameters['HttpPipelinePrepend'] | Foreach-Object { if ($_) { $testPlayback = $testPlayback -or ('NmePowershell.Runtime.PipelineMock' -eq $_.Target.GetType().FullName -and 'Playback' -eq $_.Target.Mode) } }

        $mapping = @{
            __AllParameterSets = 'NerdioManagerPowerShell.custom\New-NmeNetAppFilesAutoscaleConfigModel';
        }
        $cmdInfo = Get-Command -Name $mapping[$parameterSet]
        [NmePowershell.Runtime.MessageAttributeHelper]::ProcessCustomAttributesAtRuntime($cmdInfo, $MyInvocation, $parameterSet, $PSCmdlet)
        [NmePowershell.Runtime.MessageAttributeHelper]::ProcessPreviewMessageAttributesAtRuntime($cmdInfo, $MyInvocation, $parameterSet, $PSCmdlet)
        $wrappedCmd = $ExecutionContext.InvokeCommand.GetCommand(($mapping[$parameterSet]), [System.Management.Automation.CommandTypes]::Cmdlet)
        if ($wrappedCmd -eq $null) {
            $wrappedCmd = $ExecutionContext.InvokeCommand.GetCommand(($mapping[$parameterSet]), [System.Management.Automation.CommandTypes]::Function)
        }
        $scriptCmd = {& $wrappedCmd @PSBoundParameters}
        $steppablePipeline = $scriptCmd.GetSteppablePipeline($MyInvocation.CommandOrigin)
        $steppablePipeline.Begin($PSCmdlet)
    } catch {

        throw
    }
}

process {
    try {
        $steppablePipeline.Process($_)
    } catch {

        throw
    }

}
end {
    try {
        $steppablePipeline.End()

    } catch {

        throw
    }
} 
}
