
# ----------------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.10.8, generator: @autorest/powershell@4.0.752)
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# ----------------------------------------------------------------------------------

<#
.Synopsis
Create an in-memory object for ImageFromLibraryCreateParams.
.Description
Create an in-memory object for ImageFromLibraryCreateParams.

#>
function New-NmeImageFromLibraryCreateParamsModel {
[OutputType([NmePowershell.Models.ImageFromLibraryCreateParams])]
[CmdletBinding(PositionalBinding=$false)]
param(
    [Parameter(Mandatory)]
    [NmePowershell.PSArgumentCompleterAttribute("Clone", "Source")]
    [NmePowershell.Category('Body')]
    [System.String]
    ${ApplicationsTarget},

    [Parameter(Mandatory)]
    [NmePowershell.Category('Body')]
    [System.Int32]
    ${DiskSize},

    [Parameter(Mandatory)]
    [NmePowershell.Category('Body')]
    [System.String]
    ${ImageIdName},

    [Parameter(Mandatory)]
    [NmePowershell.Category('Body')]
    [System.String]
    ${ImageIdResourceGroup},

    [Parameter(Mandatory)]
    [NmePowershell.Category('Body')]
    [System.String]
    ${ImageIdSubscriptionId},

    [Parameter(Mandatory)]
    [NmePowershell.Category('Body')]
    [System.String]
    ${NetworkId},

    [Parameter(Mandatory)]
    [NmePowershell.PSArgumentCompleterAttribute("Clone", "Source")]
    [NmePowershell.Category('Body')]
    [System.String]
    ${ScriptedActionTarget},

    [Parameter(Mandatory)]
    [NmePowershell.Category('Body')]
    [NmePowershell.Models.IScriptedActionOption[]]
    # 
    ${ScriptedActions},

    [Parameter(Mandatory)]
    [NmePowershell.Category('Body')]
    [System.String]
    ${SourceImageId},

    [Parameter(Mandatory)]
    [NmePowershell.Category('Body')]
    [System.String]
    ${StorageType},

    [Parameter(Mandatory)]
    [NmePowershell.Category('Body')]
    [System.String]
    ${Subnet},

    [Parameter(Mandatory)]
    [NmePowershell.Category('Body')]
    [System.String]
    ${VMSize},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.Int32]
    ${AdConfigId},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.String]
    ${Description},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.String]
    ${DiskPerformanceTier},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.Boolean]
    ${EnableAppvClientService},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.Boolean]
    ${EnableTimezoneRedirection},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.String]
    ${GalleryImageGalleryId},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.Boolean]
    ${GalleryImageHibernationSupported},

    [Parameter()]
    [NmePowershell.PSArgumentCompleterAttribute("Generalized", "Specialized")]
    [NmePowershell.Category('Body')]
    [System.String]
    ${GalleryImageOSState},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.Int32]
    ${GalleryImageReplicaCount},

    [Parameter()]
    [NmePowershell.PSArgumentCompleterAttribute("None", "TrustedLaunch", "Confidential", "TrustedLaunchSupported", "ConfidentialSupported", "TrustedLaunchAndConfidentialSupported")]
    [NmePowershell.Category('Body')]
    [System.String]
    ${GalleryImageSecurityType},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.Boolean]
    ${GalleryImageSetInactive},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.String[]]
    ${GalleryImageTargetRegions},

    [Parameter()]
    [NmePowershell.PSArgumentCompleterAttribute("Major", "Minor", "Revision")]
    [NmePowershell.Category('Body')]
    [System.String]
    ${GalleryImageVersionIncrementType},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.Boolean]
    ${InstallCertificates},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.Boolean]
    ${LocalAdminCredentialsDisableAccount},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.String]
    ${LocalAdminCredentialsPassword},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.String]
    ${LocalAdminCredentialsUserName},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.Boolean]
    ${NoImageObjectRequired},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.Boolean]
    ${SecurityProfileSecureBootEnabled},

    [Parameter()]
    [NmePowershell.PSArgumentCompleterAttribute("None", "TrustedLaunch", "Confidential")]
    [NmePowershell.Category('Body')]
    [System.String]
    ${SecurityProfileSecurityType},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.Boolean]
    ${SecurityProfileVTpmEnabled},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.Boolean]
    ${SkipRemoveProfiles},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [NmePowershell.Models.IImageFromLibraryCreateParamsTags]
    # Dictionary of <string>.
    ${Tags},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.Boolean]
    ${UninstallFsLogix},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.String]
    ${VMTimezone}
)

begin {
    try {
        $outBuffer = $null
        if ($PSBoundParameters.TryGetValue('OutBuffer', [ref]$outBuffer)) {
            $PSBoundParameters['OutBuffer'] = 1
        }
        $parameterSet = $PSCmdlet.ParameterSetName
        
        $testPlayback = $false
        $PSBoundParameters['HttpPipelinePrepend'] | Foreach-Object { if ($_) { $testPlayback = $testPlayback -or ('NmePowershell.Runtime.PipelineMock' -eq $_.Target.GetType().FullName -and 'Playback' -eq $_.Target.Mode) } }

        $mapping = @{
            __AllParameterSets = 'NerdioManagerPowerShell.custom\New-NmeImageFromLibraryCreateParamsModel';
        }
        $cmdInfo = Get-Command -Name $mapping[$parameterSet]
        [NmePowershell.Runtime.MessageAttributeHelper]::ProcessCustomAttributesAtRuntime($cmdInfo, $MyInvocation, $parameterSet, $PSCmdlet)
        [NmePowershell.Runtime.MessageAttributeHelper]::ProcessPreviewMessageAttributesAtRuntime($cmdInfo, $MyInvocation, $parameterSet, $PSCmdlet)
        $wrappedCmd = $ExecutionContext.InvokeCommand.GetCommand(($mapping[$parameterSet]), [System.Management.Automation.CommandTypes]::Cmdlet)
        if ($wrappedCmd -eq $null) {
            $wrappedCmd = $ExecutionContext.InvokeCommand.GetCommand(($mapping[$parameterSet]), [System.Management.Automation.CommandTypes]::Function)
        }
        $scriptCmd = {& $wrappedCmd @PSBoundParameters}
        $steppablePipeline = $scriptCmd.GetSteppablePipeline($MyInvocation.CommandOrigin)
        $steppablePipeline.Begin($PSCmdlet)
    } catch {

        throw
    }
}

process {
    try {
        $steppablePipeline.Process($_)
    } catch {

        throw
    }

}
end {
    try {
        $steppablePipeline.End()

    } catch {

        throw
    }
} 
}
