
# ----------------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.10.8, generator: @autorest/powershell@4.0.752)
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# ----------------------------------------------------------------------------------

<#
.Synopsis
Create an in-memory object for TempVm.
.Description
Create an in-memory object for TempVm.

#>
function New-NmeTempVmModel {
[OutputType([NmePowershell.Models.TempVm])]
[CmdletBinding(PositionalBinding=$false)]
param(
    [Parameter(Mandatory)]
    [NmePowershell.Category('Body')]
    [System.Int32]
    ${DiskSize},

    [Parameter(Mandatory)]
    [NmePowershell.Category('Body')]
    [System.String]
    ${Image},

    [Parameter(Mandatory)]
    [NmePowershell.Category('Body')]
    [System.String]
    ${StorageType},

    [Parameter(Mandatory)]
    [NmePowershell.Category('Body')]
    [System.String]
    ${VMIdName},

    [Parameter(Mandatory)]
    [NmePowershell.Category('Body')]
    [System.String]
    ${VMSize},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.String]
    ${DiskPerformanceTier},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.String]
    ${NetworkId},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.String]
    ${Subnet},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.String]
    ${VMIdResourceGroup},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.String]
    ${VMIdSubscriptionId}
)

begin {
    try {
        $outBuffer = $null
        if ($PSBoundParameters.TryGetValue('OutBuffer', [ref]$outBuffer)) {
            $PSBoundParameters['OutBuffer'] = 1
        }
        $parameterSet = $PSCmdlet.ParameterSetName
        
        $testPlayback = $false
        $PSBoundParameters['HttpPipelinePrepend'] | Foreach-Object { if ($_) { $testPlayback = $testPlayback -or ('NmePowershell.Runtime.PipelineMock' -eq $_.Target.GetType().FullName -and 'Playback' -eq $_.Target.Mode) } }

        $mapping = @{
            __AllParameterSets = 'NerdioManagerPowerShell.custom\New-NmeTempVmModel';
        }
        $cmdInfo = Get-Command -Name $mapping[$parameterSet]
        [NmePowershell.Runtime.MessageAttributeHelper]::ProcessCustomAttributesAtRuntime($cmdInfo, $MyInvocation, $parameterSet, $PSCmdlet)
        [NmePowershell.Runtime.MessageAttributeHelper]::ProcessPreviewMessageAttributesAtRuntime($cmdInfo, $MyInvocation, $parameterSet, $PSCmdlet)
        $wrappedCmd = $ExecutionContext.InvokeCommand.GetCommand(($mapping[$parameterSet]), [System.Management.Automation.CommandTypes]::Cmdlet)
        if ($wrappedCmd -eq $null) {
            $wrappedCmd = $ExecutionContext.InvokeCommand.GetCommand(($mapping[$parameterSet]), [System.Management.Automation.CommandTypes]::Function)
        }
        $scriptCmd = {& $wrappedCmd @PSBoundParameters}
        $steppablePipeline = $scriptCmd.GetSteppablePipeline($MyInvocation.CommandOrigin)
        $steppablePipeline.Begin($PSCmdlet)
    } catch {

        throw
    }
}

process {
    try {
        $steppablePipeline.Process($_)
    } catch {

        throw
    }

}
end {
    try {
        $steppablePipeline.End()

    } catch {

        throw
    }
} 
}
