
# ----------------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.10.8, generator: @autorest/powershell@4.0.752)
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# ----------------------------------------------------------------------------------

<#
.Synopsis
Create an in-memory object for NetAppFilesBasicAutoscaleConfigUpdate.
.Description
Create an in-memory object for NetAppFilesBasicAutoscaleConfigUpdate.

#>
function New-NmeNetAppFilesBasicAutoscaleConfigUpdateModel {
[OutputType([NmePowershell.Models.NetAppFilesBasicAutoscaleConfigUpdate])]
[CmdletBinding(PositionalBinding=$false)]
param(
    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.Int32]
    ${MaxSizeBuffer},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.Int32]
    ${MaxSizeLimit},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.Double]
    ${MinSizeBuffer},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.Boolean]
    ${NonGreedyStrategicEnabled},

    [Parameter()]
    [NmePowershell.PSArgumentCompleterAttribute("VolumeOnly", "VolumeAndPool")]
    [NmePowershell.Category('Body')]
    [System.String]
    ${ScalingMode},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.Boolean]
    ${TriggerLimitExceedingError}
)

begin {
    try {
        $outBuffer = $null
        if ($PSBoundParameters.TryGetValue('OutBuffer', [ref]$outBuffer)) {
            $PSBoundParameters['OutBuffer'] = 1
        }
        $parameterSet = $PSCmdlet.ParameterSetName
        
        $testPlayback = $false
        $PSBoundParameters['HttpPipelinePrepend'] | Foreach-Object { if ($_) { $testPlayback = $testPlayback -or ('NmePowershell.Runtime.PipelineMock' -eq $_.Target.GetType().FullName -and 'Playback' -eq $_.Target.Mode) } }

        $mapping = @{
            __AllParameterSets = 'NerdioManagerPowerShell.custom\New-NmeNetAppFilesBasicAutoscaleConfigUpdateModel';
        }
        $cmdInfo = Get-Command -Name $mapping[$parameterSet]
        [NmePowershell.Runtime.MessageAttributeHelper]::ProcessCustomAttributesAtRuntime($cmdInfo, $MyInvocation, $parameterSet, $PSCmdlet)
        [NmePowershell.Runtime.MessageAttributeHelper]::ProcessPreviewMessageAttributesAtRuntime($cmdInfo, $MyInvocation, $parameterSet, $PSCmdlet)
        $wrappedCmd = $ExecutionContext.InvokeCommand.GetCommand(($mapping[$parameterSet]), [System.Management.Automation.CommandTypes]::Cmdlet)
        if ($wrappedCmd -eq $null) {
            $wrappedCmd = $ExecutionContext.InvokeCommand.GetCommand(($mapping[$parameterSet]), [System.Management.Automation.CommandTypes]::Function)
        }
        $scriptCmd = {& $wrappedCmd @PSBoundParameters}
        $steppablePipeline = $scriptCmd.GetSteppablePipeline($MyInvocation.CommandOrigin)
        $steppablePipeline.Begin($PSCmdlet)
    } catch {

        throw
    }
}

process {
    try {
        $steppablePipeline.Process($_)
    } catch {

        throw
    }

}
end {
    try {
        $steppablePipeline.End()

    } catch {

        throw
    }
} 
}
