
# ----------------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.10.8, generator: @autorest/powershell@4.0.752)
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# ----------------------------------------------------------------------------------

<#
.Synopsis
Create an in-memory object for SetAsImageParams.
.Description
Create an in-memory object for SetAsImageParams.

#>
function New-NmeSetAsImageParamsModel {
[OutputType([NmePowershell.Models.SetAsImageParams])]
[CmdletBinding(PositionalBinding=$false)]
param(
    [Parameter(Mandatory)]
    [NmePowershell.PSArgumentCompleterAttribute("Clone", "Source")]
    [NmePowershell.Category('Body')]
    [System.String]
    ${ApplicationsTarget},

    [Parameter(Mandatory)]
    [NmePowershell.PSArgumentCompleterAttribute("Clone", "Source")]
    [NmePowershell.Category('Body')]
    [System.String]
    ${ScriptedActionTarget},

    [Parameter(Mandatory)]
    [NmePowershell.Category('Body')]
    [NmePowershell.Models.IScriptedActionOption[]]
    # 
    ${ScriptedActions},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.String]
    ${Changelog},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.Boolean]
    ${EnableAppvClientService},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.String]
    ${GalleryImageGalleryId},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.Boolean]
    ${GalleryImageHibernationSupported},

    [Parameter()]
    [NmePowershell.PSArgumentCompleterAttribute("Generalized", "Specialized")]
    [NmePowershell.Category('Body')]
    [System.String]
    ${GalleryImageOSState},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.Int32]
    ${GalleryImageReplicaCount},

    [Parameter()]
    [NmePowershell.PSArgumentCompleterAttribute("None", "TrustedLaunch", "Confidential", "TrustedLaunchSupported", "ConfidentialSupported", "TrustedLaunchAndConfidentialSupported")]
    [NmePowershell.Category('Body')]
    [System.String]
    ${GalleryImageSecurityType},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.Boolean]
    ${GalleryImageSetInactive},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.String[]]
    ${GalleryImageTargetRegions},

    [Parameter()]
    [NmePowershell.PSArgumentCompleterAttribute("Major", "Minor", "Revision")]
    [NmePowershell.Category('Body')]
    [System.String]
    ${GalleryImageVersionIncrementType},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.Boolean]
    ${InstallCertificates},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.Boolean]
    ${PowerOnVM},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.Boolean]
    ${RetainOldImage},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.Boolean]
    ${SkipRemoveProfiles},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [NmePowershell.Models.ISetAsImageParamsTags]
    # Dictionary of <string>.
    ${Tags}
)

begin {
    try {
        $outBuffer = $null
        if ($PSBoundParameters.TryGetValue('OutBuffer', [ref]$outBuffer)) {
            $PSBoundParameters['OutBuffer'] = 1
        }
        $parameterSet = $PSCmdlet.ParameterSetName
        
        $testPlayback = $false
        $PSBoundParameters['HttpPipelinePrepend'] | Foreach-Object { if ($_) { $testPlayback = $testPlayback -or ('NmePowershell.Runtime.PipelineMock' -eq $_.Target.GetType().FullName -and 'Playback' -eq $_.Target.Mode) } }

        $mapping = @{
            __AllParameterSets = 'NerdioManagerPowerShell.custom\New-NmeSetAsImageParamsModel';
        }
        $cmdInfo = Get-Command -Name $mapping[$parameterSet]
        [NmePowershell.Runtime.MessageAttributeHelper]::ProcessCustomAttributesAtRuntime($cmdInfo, $MyInvocation, $parameterSet, $PSCmdlet)
        [NmePowershell.Runtime.MessageAttributeHelper]::ProcessPreviewMessageAttributesAtRuntime($cmdInfo, $MyInvocation, $parameterSet, $PSCmdlet)
        $wrappedCmd = $ExecutionContext.InvokeCommand.GetCommand(($mapping[$parameterSet]), [System.Management.Automation.CommandTypes]::Cmdlet)
        if ($wrappedCmd -eq $null) {
            $wrappedCmd = $ExecutionContext.InvokeCommand.GetCommand(($mapping[$parameterSet]), [System.Management.Automation.CommandTypes]::Function)
        }
        $scriptCmd = {& $wrappedCmd @PSBoundParameters}
        $steppablePipeline = $scriptCmd.GetSteppablePipeline($MyInvocation.CommandOrigin)
        $steppablePipeline.Begin($PSCmdlet)
    } catch {

        throw
    }
}

process {
    try {
        $steppablePipeline.Process($_)
    } catch {

        throw
    }

}
end {
    try {
        $steppablePipeline.End()

    } catch {

        throw
    }
} 
}
