
# ----------------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.10.8, generator: @autorest/powershell@4.0.752)
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# ----------------------------------------------------------------------------------

<#
.Synopsis
Create an in-memory object for AvdAgentUpdate.
.Description
Create an in-memory object for AvdAgentUpdate.

#>
function New-NmeAvdAgentUpdateModel {
[OutputType([NmePowershell.Models.AvdAgentUpdate])]
[CmdletBinding(PositionalBinding=$false)]
param(
    [Parameter(Mandatory)]
    [NmePowershell.Category('Body')]
    [System.Boolean]
    ${ExcludeDrainModeHosts},

    [Parameter(Mandatory)]
    [NmePowershell.Category('Body')]
    [System.Boolean]
    ${PowerOnHostsInMaintenanceWindow},

    [Parameter(Mandatory)]
    [NmePowershell.PSArgumentCompleterAttribute("Default", "Scheduled")]
    [NmePowershell.Category('Body')]
    [System.String]
    ${Type},

    [Parameter(Mandatory)]
    [NmePowershell.Category('Body')]
    [System.Boolean]
    ${UseSessionHostLocalTime},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.String]
    ${MaintenanceWindowTimeZone},

    [Parameter()]
    [NmePowershell.PSArgumentCompleterAttribute("0", "1", "2", "3", "4", "5", "6")]
    [NmePowershell.Category('Body')]
    [System.Int32]
    ${PrimaryWindowDayOfWeek},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.Int32]
    ${PrimaryWindowHour},

    [Parameter()]
    [NmePowershell.PSArgumentCompleterAttribute("0", "1", "2", "3", "4", "5", "6")]
    [NmePowershell.Category('Body')]
    [System.Int32]
    ${SecondaryWindowDayOfWeek},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.Int32]
    ${SecondaryWindowHour}
)

begin {
    try {
        $outBuffer = $null
        if ($PSBoundParameters.TryGetValue('OutBuffer', [ref]$outBuffer)) {
            $PSBoundParameters['OutBuffer'] = 1
        }
        $parameterSet = $PSCmdlet.ParameterSetName
        
        $testPlayback = $false
        $PSBoundParameters['HttpPipelinePrepend'] | Foreach-Object { if ($_) { $testPlayback = $testPlayback -or ('NmePowershell.Runtime.PipelineMock' -eq $_.Target.GetType().FullName -and 'Playback' -eq $_.Target.Mode) } }

        $mapping = @{
            __AllParameterSets = 'NerdioManagerPowerShell.custom\New-NmeAvdAgentUpdateModel';
        }
        $cmdInfo = Get-Command -Name $mapping[$parameterSet]
        [NmePowershell.Runtime.MessageAttributeHelper]::ProcessCustomAttributesAtRuntime($cmdInfo, $MyInvocation, $parameterSet, $PSCmdlet)
        [NmePowershell.Runtime.MessageAttributeHelper]::ProcessPreviewMessageAttributesAtRuntime($cmdInfo, $MyInvocation, $parameterSet, $PSCmdlet)
        $wrappedCmd = $ExecutionContext.InvokeCommand.GetCommand(($mapping[$parameterSet]), [System.Management.Automation.CommandTypes]::Cmdlet)
        if ($wrappedCmd -eq $null) {
            $wrappedCmd = $ExecutionContext.InvokeCommand.GetCommand(($mapping[$parameterSet]), [System.Management.Automation.CommandTypes]::Function)
        }
        $scriptCmd = {& $wrappedCmd @PSBoundParameters}
        $steppablePipeline = $scriptCmd.GetSteppablePipeline($MyInvocation.CommandOrigin)
        $steppablePipeline.Begin($PSCmdlet)
    } catch {

        throw
    }
}

process {
    try {
        $steppablePipeline.Process($_)
    } catch {

        throw
    }

}
end {
    try {
        $steppablePipeline.End()

    } catch {

        throw
    }
} 
}
