
# ----------------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.10.8, generator: @autorest/powershell@4.0.752)
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# ----------------------------------------------------------------------------------

<#
.Synopsis
Create an in-memory object for HostPoolFsLogixProperties.
.Description
Create an in-memory object for HostPoolFsLogixProperties.

#>
function New-NmeHostPoolFsLogixPropertiesModel {
[OutputType([NmePowershell.Models.HostPoolFsLogixProperties])]
[CmdletBinding(PositionalBinding=$false)]
param(
    [Parameter(Mandatory)]
    [NmePowershell.Category('Body')]
    [System.Boolean]
    ${CloudCacheEnabled},

    [Parameter(Mandatory)]
    [NmePowershell.PSArgumentCompleterAttribute("None", "Admins")]
    [NmePowershell.Category('Body')]
    [System.String]
    ${ExclusionMode},

    [Parameter(Mandatory)]
    [NmePowershell.Category('Body')]
    [System.Boolean]
    ${ForceUpdate},

    [Parameter(Mandatory)]
    [NmePowershell.Category('Body')]
    [System.Boolean]
    ${PageBlobs},

    [Parameter(Mandatory)]
    [NmePowershell.Category('Body')]
    [System.String]
    ${ProfilesPath},

    [Parameter(Mandatory)]
    [NmePowershell.Category('Body')]
    [System.String]
    ${RegistryOptions},

    [Parameter(Mandatory)]
    [NmePowershell.Category('Body')]
    [System.Boolean]
    ${SetupRegistryForAadJoinedStorage},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.String]
    ${AppServiceRegistryOptionRegistryOptions},

    [Parameter()]
    [NmePowershell.PSArgumentCompleterAttribute("None", "Apply")]
    [NmePowershell.Category('Body')]
    [System.String]
    ${AppServiceRegistryOptionRegistryOptionsMode},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.String]
    ${CloudCacheOfficeRegistryOptions},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.String]
    ${CloudCacheProfileRegistryOptions},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.String]
    ${CloudCacheRegistryOptions},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.String[]]
    ${ExclusionExcludedDomainAccounts},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.String]
    # FSLogix version.
    #         null means "use the latest stable version".
    ${FsLogixVersion},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.String]
    ${LogRegistryOptionRegistryOptions},

    [Parameter()]
    [NmePowershell.PSArgumentCompleterAttribute("None", "Apply")]
    [NmePowershell.Category('Body')]
    [System.String]
    ${LogRegistryOptionRegistryOptionsMode},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.String]
    ${OfficeContainerPath},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.String]
    ${OfficeContainerRegistryOptions},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.String]
    ${RedirectionsXml},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.String]
    ${SecondaryOfficeContainerPath},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.String]
    ${SecondaryProfilesPath}
)

begin {
    try {
        $outBuffer = $null
        if ($PSBoundParameters.TryGetValue('OutBuffer', [ref]$outBuffer)) {
            $PSBoundParameters['OutBuffer'] = 1
        }
        $parameterSet = $PSCmdlet.ParameterSetName
        
        $testPlayback = $false
        $PSBoundParameters['HttpPipelinePrepend'] | Foreach-Object { if ($_) { $testPlayback = $testPlayback -or ('NmePowershell.Runtime.PipelineMock' -eq $_.Target.GetType().FullName -and 'Playback' -eq $_.Target.Mode) } }

        $mapping = @{
            __AllParameterSets = 'NerdioManagerPowerShell.custom\New-NmeHostPoolFsLogixPropertiesModel';
        }
        $cmdInfo = Get-Command -Name $mapping[$parameterSet]
        [NmePowershell.Runtime.MessageAttributeHelper]::ProcessCustomAttributesAtRuntime($cmdInfo, $MyInvocation, $parameterSet, $PSCmdlet)
        [NmePowershell.Runtime.MessageAttributeHelper]::ProcessPreviewMessageAttributesAtRuntime($cmdInfo, $MyInvocation, $parameterSet, $PSCmdlet)
        $wrappedCmd = $ExecutionContext.InvokeCommand.GetCommand(($mapping[$parameterSet]), [System.Management.Automation.CommandTypes]::Cmdlet)
        if ($wrappedCmd -eq $null) {
            $wrappedCmd = $ExecutionContext.InvokeCommand.GetCommand(($mapping[$parameterSet]), [System.Management.Automation.CommandTypes]::Function)
        }
        $scriptCmd = {& $wrappedCmd @PSBoundParameters}
        $steppablePipeline = $scriptCmd.GetSteppablePipeline($MyInvocation.CommandOrigin)
        $steppablePipeline.Begin($PSCmdlet)
    } catch {

        throw
    }
}

process {
    try {
        $steppablePipeline.Process($_)
    } catch {

        throw
    }

}
end {
    try {
        $steppablePipeline.End()

    } catch {

        throw
    }
} 
}
