
# ----------------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.10.8, generator: @autorest/powershell@4.0.752)
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# ----------------------------------------------------------------------------------

<#
.Synopsis
Create an in-memory object for SessionHostCreateParams.
.Description
Create an in-memory object for SessionHostCreateParams.

#>
function New-NmeSessionHostCreateParamsModel {
[OutputType([NmePowershell.Models.SessionHostCreateParams])]
[CmdletBinding(PositionalBinding=$false)]
param(
    [Parameter(Mandatory)]
    [NmePowershell.Category('Body')]
    [System.Int32]
    ${HostDiskSize},

    [Parameter(Mandatory)]
    [NmePowershell.Category('Body')]
    [System.Boolean]
    ${HostHasEphemeralOSDisk},

    [Parameter(Mandatory)]
    [NmePowershell.Category('Body')]
    [System.String]
    ${HostImage},

    [Parameter(Mandatory)]
    [NmePowershell.Category('Body')]
    [System.String]
    ${HostNetworkId},

    [Parameter(Mandatory)]
    [NmePowershell.Category('Body')]
    [System.String]
    ${HostStorageType},

    [Parameter(Mandatory)]
    [NmePowershell.Category('Body')]
    [System.String]
    ${HostSubnet},

    [Parameter(Mandatory)]
    [NmePowershell.Category('Body')]
    [System.String]
    ${HostVMSize},

    [Parameter(Mandatory)]
    [NmePowershell.Category('Body')]
    [System.Boolean]
    # Define the name assigning behaviour.
    #         false: Host will have name with the exact 'Name' value;
    #         true:  Host will have name with the 'Name-{????}' value.
    ${VMIdAddSuffix},

    [Parameter(Mandatory)]
    [NmePowershell.Category('Body')]
    [System.String]
    ${VMIdName},

    [Parameter(Mandatory)]
    [NmePowershell.Category('Body')]
    [System.String]
    ${VMIdResourceGroup},

    [Parameter(Mandatory)]
    [NmePowershell.Category('Body')]
    [System.String]
    ${VMIdSubscriptionId},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.String]
    ${HostDiskPerformanceTier},

    [Parameter()]
    [NmePowershell.PSArgumentCompleterAttribute("CacheDisk", "ResourceDisk", "NvmeDisk")]
    [NmePowershell.Category('Body')]
    [System.String]
    ${HostEphemeralOSDiskPlacement},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.Int32]
    ${HostsCount},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [NmePowershell.Models.ISessionHostCreateParamsTags]
    # Dictionary of <string>.
    ${Tags},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.String]
    ${UserToAssign}
)

begin {
    try {
        $outBuffer = $null
        if ($PSBoundParameters.TryGetValue('OutBuffer', [ref]$outBuffer)) {
            $PSBoundParameters['OutBuffer'] = 1
        }
        $parameterSet = $PSCmdlet.ParameterSetName
        
        $testPlayback = $false
        $PSBoundParameters['HttpPipelinePrepend'] | Foreach-Object { if ($_) { $testPlayback = $testPlayback -or ('NmePowershell.Runtime.PipelineMock' -eq $_.Target.GetType().FullName -and 'Playback' -eq $_.Target.Mode) } }

        $mapping = @{
            __AllParameterSets = 'NerdioManagerPowerShell.custom\New-NmeSessionHostCreateParamsModel';
        }
        $cmdInfo = Get-Command -Name $mapping[$parameterSet]
        [NmePowershell.Runtime.MessageAttributeHelper]::ProcessCustomAttributesAtRuntime($cmdInfo, $MyInvocation, $parameterSet, $PSCmdlet)
        [NmePowershell.Runtime.MessageAttributeHelper]::ProcessPreviewMessageAttributesAtRuntime($cmdInfo, $MyInvocation, $parameterSet, $PSCmdlet)
        $wrappedCmd = $ExecutionContext.InvokeCommand.GetCommand(($mapping[$parameterSet]), [System.Management.Automation.CommandTypes]::Cmdlet)
        if ($wrappedCmd -eq $null) {
            $wrappedCmd = $ExecutionContext.InvokeCommand.GetCommand(($mapping[$parameterSet]), [System.Management.Automation.CommandTypes]::Function)
        }
        $scriptCmd = {& $wrappedCmd @PSBoundParameters}
        $steppablePipeline = $scriptCmd.GetSteppablePipeline($MyInvocation.CommandOrigin)
        $steppablePipeline.Begin($PSCmdlet)
    } catch {

        throw
    }
}

process {
    try {
        $steppablePipeline.Process($_)
    } catch {

        throw
    }

}
end {
    try {
        $steppablePipeline.End()

    } catch {

        throw
    }
} 
}
