
# ----------------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.10.8, generator: @autorest/powershell@4.0.752)
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# ----------------------------------------------------------------------------------

<#
.Synopsis
Create an in-memory object for HostPoolReimageSchedule.
.Description
Create an in-memory object for HostPoolReimageSchedule.

#>
function New-NmeHostPoolReimageScheduleModel {
[OutputType([NmePowershell.Models.HostPoolReimageSchedule])]
[CmdletBinding(PositionalBinding=$false)]
param(
    [Parameter(Mandatory)]
    [NmePowershell.PSArgumentCompleterAttribute("Once", "Daily", "Weekly", "Monthly", "Hourly", "PatchTuesday")]
    [NmePowershell.Category('Body')]
    [System.String]
    ${ScheduleRecurrenceType},

    [Parameter(Mandatory)]
    [NmePowershell.Category('Body')]
    [System.DateTime]
    ${ScheduleStartDate},

    [Parameter(Mandatory)]
    [NmePowershell.Category('Body')]
    [System.Int32]
    ${ScheduleStartHour},

    [Parameter(Mandatory)]
    [NmePowershell.Category('Body')]
    [System.Int32]
    ${ScheduleStartMinutes},

    [Parameter(Mandatory)]
    [NmePowershell.Category('Body')]
    [System.String]
    ${ScheduleTimeZoneId},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.Int32]
    ${ConcurrencyMaxFailedTasks},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.Int32]
    ${ConcurrencyTasks},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.Boolean]
    ${MessagingDeactivateBeforeOperation},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.Int32]
    ${MessagingDelayMinutes},

    [Parameter()]
    [NmePowershell.PSArgumentCompleterAttribute("Force", "Wait")]
    [NmePowershell.Category('Body')]
    [System.String]
    ${MessagingLogOffAggressiveness},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.String]
    ${MessagingMessage},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.Int32]
    ${MessagingTimeoutInDays},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.String]
    ${ReimageParamDiskPerformanceTier},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.Int32]
    ${ReimageParamDiskSize},

    [Parameter()]
    [NmePowershell.PSArgumentCompleterAttribute("CacheDisk", "ResourceDisk", "NvmeDisk")]
    [NmePowershell.Category('Body')]
    [System.String]
    ${ReimageParamEphemeralOSDiskPlacement},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.Boolean]
    ${ReimageParamHasEphemeralOSDisk},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.String]
    ${ReimageParamImage},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.Boolean]
    ${ReimageParamSetToDrainModeWhileProcessing},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.String]
    ${ReimageParamStorageType},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.String]
    ${ReimageParamVMSize},

    [Parameter()]
    [NmePowershell.PSArgumentCompleterAttribute("0", "1", "2", "3", "4", "5", "6")]
    [NmePowershell.Category('Body')]
    [System.Int32]
    ${ScheduleDayOfWeek},

    [Parameter()]
    [NmePowershell.PSArgumentCompleterAttribute("First", "Second", "Third", "Fourth", "Last")]
    [NmePowershell.Category('Body')]
    [System.String]
    ${ScheduleDayOfWeekNumber},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.String]
    ${ScheduleDescription},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.String]
    ${ScheduleName},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.Int32]
    ${ScheduleOffsetInDays}
)

begin {
    try {
        $outBuffer = $null
        if ($PSBoundParameters.TryGetValue('OutBuffer', [ref]$outBuffer)) {
            $PSBoundParameters['OutBuffer'] = 1
        }
        $parameterSet = $PSCmdlet.ParameterSetName
        
        $testPlayback = $false
        $PSBoundParameters['HttpPipelinePrepend'] | Foreach-Object { if ($_) { $testPlayback = $testPlayback -or ('NmePowershell.Runtime.PipelineMock' -eq $_.Target.GetType().FullName -and 'Playback' -eq $_.Target.Mode) } }

        $mapping = @{
            __AllParameterSets = 'NerdioManagerPowerShell.custom\New-NmeHostPoolReimageScheduleModel';
        }
        $cmdInfo = Get-Command -Name $mapping[$parameterSet]
        [NmePowershell.Runtime.MessageAttributeHelper]::ProcessCustomAttributesAtRuntime($cmdInfo, $MyInvocation, $parameterSet, $PSCmdlet)
        [NmePowershell.Runtime.MessageAttributeHelper]::ProcessPreviewMessageAttributesAtRuntime($cmdInfo, $MyInvocation, $parameterSet, $PSCmdlet)
        $wrappedCmd = $ExecutionContext.InvokeCommand.GetCommand(($mapping[$parameterSet]), [System.Management.Automation.CommandTypes]::Cmdlet)
        if ($wrappedCmd -eq $null) {
            $wrappedCmd = $ExecutionContext.InvokeCommand.GetCommand(($mapping[$parameterSet]), [System.Management.Automation.CommandTypes]::Function)
        }
        $scriptCmd = {& $wrappedCmd @PSBoundParameters}
        $steppablePipeline = $scriptCmd.GetSteppablePipeline($MyInvocation.CommandOrigin)
        $steppablePipeline.Begin($PSCmdlet)
    } catch {

        throw
    }
}

process {
    try {
        $steppablePipeline.Process($_)
    } catch {

        throw
    }

}
end {
    try {
        $steppablePipeline.End()

    } catch {

        throw
    }
} 
}
