
# ----------------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.10.8, generator: @autorest/powershell@4.0.752)
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# ----------------------------------------------------------------------------------

<#
.Synopsis
Create an in-memory object for FsLogixPropertiesUpdate.
.Description
Create an in-memory object for FsLogixPropertiesUpdate.

#>
function New-NmeFsLogixPropertiesUpdateModel {
[OutputType([NmePowershell.Models.FsLogixPropertiesUpdate])]
[CmdletBinding(PositionalBinding=$false)]
param(
    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.String]
    ${AppServiceRegistryOptionRegistryOptions},

    [Parameter()]
    [NmePowershell.PSArgumentCompleterAttribute("None", "Apply")]
    [NmePowershell.Category('Body')]
    [System.String]
    ${AppServiceRegistryOptionRegistryOptionsMode},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.Boolean]
    ${CloudCache},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.String]
    ${CloudCacheRegistryOptionCommon},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.String]
    ${CloudCacheRegistryOptionOfficeContainer},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.String]
    ${CloudCacheRegistryOptionProfileContainer},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.Boolean]
    ${EntraIdKerberos},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.String[]]
    ${ExclusionExcludedDomainAccounts},

    [Parameter()]
    [NmePowershell.PSArgumentCompleterAttribute("None", "Admins")]
    [NmePowershell.Category('Body')]
    [System.String]
    ${ExclusionMode},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.Boolean]
    ${InstallerForceUpdate},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.String]
    ${InstallerVersion},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.String]
    ${LogRegistryOptionRegistryOptions},

    [Parameter()]
    [NmePowershell.PSArgumentCompleterAttribute("None", "Apply")]
    [NmePowershell.Category('Body')]
    [System.String]
    ${LogRegistryOptionRegistryOptionsMode},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.String[]]
    ${OfficeContainerLocations},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.String]
    ${OfficeContainerOptions},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.Boolean]
    ${PageBlobs},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.String[]]
    ${ProfileContainerLocations},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.String]
    ${ProfileContainerOptions},

    [Parameter()]
    [NmePowershell.Category('Body')]
    [System.String]
    ${RedirectionsXml}
)

begin {
    try {
        $outBuffer = $null
        if ($PSBoundParameters.TryGetValue('OutBuffer', [ref]$outBuffer)) {
            $PSBoundParameters['OutBuffer'] = 1
        }
        $parameterSet = $PSCmdlet.ParameterSetName
        
        $testPlayback = $false
        $PSBoundParameters['HttpPipelinePrepend'] | Foreach-Object { if ($_) { $testPlayback = $testPlayback -or ('NmePowershell.Runtime.PipelineMock' -eq $_.Target.GetType().FullName -and 'Playback' -eq $_.Target.Mode) } }

        $mapping = @{
            __AllParameterSets = 'NerdioManagerPowerShell.custom\New-NmeFsLogixPropertiesUpdateModel';
        }
        $cmdInfo = Get-Command -Name $mapping[$parameterSet]
        [NmePowershell.Runtime.MessageAttributeHelper]::ProcessCustomAttributesAtRuntime($cmdInfo, $MyInvocation, $parameterSet, $PSCmdlet)
        [NmePowershell.Runtime.MessageAttributeHelper]::ProcessPreviewMessageAttributesAtRuntime($cmdInfo, $MyInvocation, $parameterSet, $PSCmdlet)
        $wrappedCmd = $ExecutionContext.InvokeCommand.GetCommand(($mapping[$parameterSet]), [System.Management.Automation.CommandTypes]::Cmdlet)
        if ($wrappedCmd -eq $null) {
            $wrappedCmd = $ExecutionContext.InvokeCommand.GetCommand(($mapping[$parameterSet]), [System.Management.Automation.CommandTypes]::Function)
        }
        $scriptCmd = {& $wrappedCmd @PSBoundParameters}
        $steppablePipeline = $scriptCmd.GetSteppablePipeline($MyInvocation.CommandOrigin)
        $steppablePipeline.Begin($PSCmdlet)
    } catch {

        throw
    }
}

process {
    try {
        $steppablePipeline.Process($_)
    } catch {

        throw
    }

}
end {
    try {
        $steppablePipeline.End()

    } catch {

        throw
    }
} 
}
