
# ----------------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.10.8, generator: @autorest/powershell@4.0.752)
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# ----------------------------------------------------------------------------------

<#
.Synopsis
Set auto-scale config for ARM host pool
.Description
Set auto-scale config for ARM host pool

#>
function Set-NmeHostPoolAutoScale {
[OutputType([NmePowershell.Models.IResponseWithJob])]
[CmdletBinding(DefaultParameterSetName='SetExpanded', PositionalBinding=$false, SupportsShouldProcess, ConfirmImpact='Medium')]
param(
    [Parameter(Mandatory)]
    [NmePowershell.Category('Path')]
    [System.String]
    # .
    ${HostPoolName},

    [Parameter(Mandatory)]
    [NmePowershell.Category('Path')]
    [System.String]
    # .
    ${ResourceGroup},

    [Parameter(Mandatory)]
    [NmePowershell.Category('Path')]
    [System.String]
    # .
    ${SubscriptionId},

    [Parameter(Mandatory)]
    [NmePowershell.Category('Query')]
    [System.Management.Automation.SwitchParameter]
    # .
    ${MultiTriggers},

    [Parameter(ParameterSetName='Set', Mandatory, ValueFromPipeline)]
    [NmePowershell.Category('Body')]
    [NmePowershell.Models.IDynamicPoolConfiguration]
    # .
    ${Body},

    [Parameter(ParameterSetName='SetExpanded', Mandatory)]
    [NmePowershell.PSArgumentCompleterAttribute("Running", "AvailableForConnection")]
    [NmePowershell.Category('Body')]
    [System.String]
    # .
    ${ActiveHostType},

    [Parameter(ParameterSetName='SetExpanded', Mandatory)]
    [NmePowershell.Category('Body')]
    [System.Management.Automation.SwitchParameter]
    # .
    ${AutoHealEnable},

    [Parameter(ParameterSetName='SetExpanded', Mandatory)]
    [NmePowershell.Category('Body')]
    [System.Int32]
    # .
    ${BurstCapacity},

    [Parameter(ParameterSetName='SetExpanded', Mandatory)]
    [NmePowershell.Category('Body')]
    [System.Int32]
    # .
    ${HostPoolCapacity},

    [Parameter(ParameterSetName='SetExpanded', Mandatory)]
    [NmePowershell.Category('Body')]
    [System.Management.Automation.SwitchParameter]
    # .
    ${IsEnabled},

    [Parameter(ParameterSetName='SetExpanded', Mandatory)]
    [NmePowershell.Category('Body')]
    [System.Management.Automation.SwitchParameter]
    # .
    ${IsSingleUserDesktop},

    [Parameter(ParameterSetName='SetExpanded', Mandatory)]
    [NmePowershell.Category('Body')]
    [System.Int32]
    # .
    ${MinActiveHostsCount},

    [Parameter(ParameterSetName='SetExpanded', Mandatory)]
    [NmePowershell.Category('Body')]
    [System.Management.Automation.SwitchParameter]
    # .
    ${PreStageHostEnable},

    [Parameter(ParameterSetName='SetExpanded', Mandatory)]
    [NmePowershell.Category('Body')]
    [System.Management.Automation.SwitchParameter]
    # .
    ${ReImageUsedHosts},

    [Parameter(ParameterSetName='SetExpanded', Mandatory)]
    [NmePowershell.PSArgumentCompleterAttribute("Disabled", "Always", "OnlyWhenScaleInIsAllowed")]
    [NmePowershell.Category('Body')]
    [System.String]
    # .
    ${ReImageUsedHostsMode},

    [Parameter(ParameterSetName='SetExpanded', Mandatory)]
    [NmePowershell.PSArgumentCompleterAttribute("High", "Medium", "Low")]
    [NmePowershell.Category('Body')]
    [System.String]
    # .
    ${ScaleInAggressiveness},

    [Parameter(ParameterSetName='SetExpanded', Mandatory)]
    [NmePowershell.Category('Body')]
    [System.Management.Automation.SwitchParameter]
    # .
    ${ScaleInRestrictionEnable},

    [Parameter(ParameterSetName='SetExpanded', Mandatory)]
    [NmePowershell.Category('Body')]
    [System.Management.Automation.SwitchParameter]
    # .
    ${ScaleInRestrictionPutToDrainMode},

    [Parameter(ParameterSetName='SetExpanded', Mandatory)]
    [NmePowershell.PSArgumentCompleterAttribute("Default", "WorkingHours", "UserDriven")]
    [NmePowershell.Category('Body')]
    [System.String]
    # .
    ${ScalingMode},

    [Parameter(ParameterSetName='SetExpanded')]
    [NmePowershell.Category('Body')]
    [System.Int32]
    # .
    ${ActiveSessionsScaleCriteriaScaleInHostChangeCount},

    [Parameter(ParameterSetName='SetExpanded')]
    [NmePowershell.Category('Body')]
    [System.Single]
    # .
    ${ActiveSessionsScaleCriteriaScaleInValue},

    [Parameter(ParameterSetName='SetExpanded')]
    [NmePowershell.Category('Body')]
    [System.Int32]
    # .
    ${ActiveSessionsScaleCriteriaScaleOutHostChangeCount},

    [Parameter(ParameterSetName='SetExpanded')]
    [NmePowershell.Category('Body')]
    [System.Single]
    # .
    ${ActiveSessionsScaleCriteriaScaleOutValue},

    [Parameter(ParameterSetName='SetExpanded')]
    [AllowEmptyCollection()]
    [NmePowershell.Category('Body')]
    [System.String[]]
    # .
    ${AdditionalNetworks},

    [Parameter(ParameterSetName='SetExpanded')]
    [AllowEmptyCollection()]
    [NmePowershell.Category('Body')]
    [NmePowershell.Models.IAutoHealConfigurationItem[]]
    # .
    ${AutoHealConfigs},

    [Parameter(ParameterSetName='SetExpanded')]
    [NmePowershell.PSArgumentCompleterAttribute("CPUUsage", "RAMUsage", "AvgActiveSessions", "AvailableUserSessionSingle", "AvailableUserSessions", "UserDriven", "PersonalAutoGrow", "PersonalAutoShrink")]
    [NmePowershell.Category('Body')]
    [System.String]
    # .
    ${AutoScaleCriteria},

    [Parameter(ParameterSetName='SetExpanded')]
    [NmePowershell.Category('Body')]
    [System.Int32]
    # .
    ${AutoScaleInterval},

    [Parameter(ParameterSetName='SetExpanded')]
    [AllowEmptyCollection()]
    [NmePowershell.Category('Body')]
    [NmePowershell.Models.IDynamicPoolTriggerInfo[]]
    # .
    ${AutoScaleTriggers},

    [Parameter(ParameterSetName='SetExpanded')]
    [NmePowershell.PSArgumentCompleterAttribute("Always", "DuringWorkHours")]
    [NmePowershell.Category('Body')]
    [System.String]
    # .
    ${AvailableUserSessionScaleCriterionAvailableSessionRestriction},

    [Parameter(ParameterSetName='SetExpanded')]
    [NmePowershell.Category('Body')]
    [System.String]
    # .
    ${AvailableUserSessionScaleCriterionEndWorkHours},

    [Parameter(ParameterSetName='SetExpanded')]
    [NmePowershell.Category('Body')]
    [System.Int32]
    # .
    ${AvailableUserSessionScaleCriterionMaxAvailableUserSessions},

    [Parameter(ParameterSetName='SetExpanded')]
    [NmePowershell.Category('Body')]
    [System.Int32]
    # .
    ${AvailableUserSessionScaleCriterionMinAvailableUserSessions},

    [Parameter(ParameterSetName='SetExpanded')]
    [NmePowershell.Category('Body')]
    [System.Int32]
    # .
    ${AvailableUserSessionScaleCriterionOutsideWorkHoursSessions},

    [Parameter(ParameterSetName='SetExpanded')]
    [AllowEmptyCollection()]
    [NmePowershell.Category('Body')]
    [NmePowershell.Models.IAutoHealAction[]]
    # .
    ${ConfigActions},

    [Parameter(ParameterSetName='SetExpanded')]
    [AllowEmptyCollection()]
    [NmePowershell.PSArgumentCompleterAttribute("0", "1", "2", "3", "4", "5", "6")]
    [NmePowershell.Category('Body')]
    [System.Int32[]]
    # .
    ${ConfigDays},

    [Parameter(ParameterSetName='SetExpanded')]
    [NmePowershell.Category('Body')]
    [System.Int32]
    # .
    ${ConfigHostsToBeReady},

    [Parameter(ParameterSetName='SetExpanded')]
    [NmePowershell.PSArgumentCompleterAttribute("Count", "Percent")]
    [NmePowershell.Category('Body')]
    [System.String]
    # .
    ${ConfigHostsToBeReadyMeasureType},

    [Parameter(ParameterSetName='SetExpanded')]
    [NmePowershell.Category('Body')]
    [System.String]
    # .
    ${ConfigNetworkId},

    [Parameter(ParameterSetName='SetExpanded')]
    [NmePowershell.Category('Body')]
    [System.Management.Automation.SwitchParameter]
    # .
    ${ConfigPreStageDiskType},

    [Parameter(ParameterSetName='SetExpanded')]
    [NmePowershell.Category('Body')]
    [System.Management.Automation.SwitchParameter]
    # .
    ${ConfigPreStageUnassigned},

    [Parameter(ParameterSetName='SetExpanded')]
    [NmePowershell.Category('Body')]
    [System.Management.Automation.SwitchParameter]
    # .
    ${ConfigPreStageUnassignedHosts},

    [Parameter(ParameterSetName='SetExpanded')]
    [NmePowershell.Category('Body')]
    [System.String]
    # .
    ${ConfigPrefix},

    [Parameter(ParameterSetName='SetExpanded')]
    [NmePowershell.Category('Body')]
    [System.String]
    # .
    ${ConfigResourceGroupId},

    [Parameter(ParameterSetName='SetExpanded')]
    [NmePowershell.PSArgumentCompleterAttribute("WithoutSessions", "WithoutActive", "WithActive")]
    [NmePowershell.Category('Body')]
    [System.String]
    # .
    ${ConfigSessionCriteria},

    [Parameter(ParameterSetName='SetExpanded')]
    [NmePowershell.Category('Body')]
    [System.Int32]
    # .
    ${ConfigStaleHeartbeatMinutes},

    [Parameter(ParameterSetName='SetExpanded')]
    [NmePowershell.Category('Body')]
    [System.String]
    # .
    ${ConfigSubnet},

    [Parameter(ParameterSetName='SetExpanded')]
    [NmePowershell.Category('Body')]
    [System.Int32]
    # .
    ${ConfigWaitMinutes},

    [Parameter(ParameterSetName='SetExpanded')]
    [NmePowershell.Category('Body')]
    [System.Int32]
    # .
    ${ConfigWaitMinutesBeforeFirstAction},

    [Parameter(ParameterSetName='SetExpanded')]
    [AllowEmptyCollection()]
    [NmePowershell.PSArgumentCompleterAttribute("Available", "Unavailable", "Shutdown", "Disconnected", "Upgrading", "UpgradeFailed", "NoHeartbeat", "NotJoinedToDomain", "DomainTrustRelationshipLost", "SxSStackListenerNotReady", "FSLogixNotHealthy", "NeedsAssistance")]
    [NmePowershell.Category('Body')]
    [System.String[]]
    # .
    ${ConfigWvdStatuses},

    [Parameter(ParameterSetName='SetExpanded')]
    [NmePowershell.PSArgumentCompleterAttribute("BreadthFirst", "DepthFirst", "Persistent", "MultiplePersistent")]
    [NmePowershell.Category('Body')]
    [System.String]
    # .
    ${ExtensionLoadBalancing},

    [Parameter(ParameterSetName='SetExpanded')]
    [NmePowershell.Category('Body')]
    [System.Int32]
    # .
    ${ExtensionMaxSessionsPerHost},

    [Parameter(ParameterSetName='SetExpanded')]
    [NmePowershell.Category('Body')]
    [System.Management.Automation.SwitchParameter]
    # .
    ${ExtensionStartVMOnConnect},

    [Parameter(ParameterSetName='SetExpanded')]
    [NmePowershell.Category('Body')]
    [System.Int32]
    # .
    ${HostUsageScaleCriteriaScaleInHostChangeCount},

    [Parameter(ParameterSetName='SetExpanded')]
    [NmePowershell.Category('Body')]
    [System.Single]
    # .
    ${HostUsageScaleCriteriaScaleInValue},

    [Parameter(ParameterSetName='SetExpanded')]
    [NmePowershell.Category('Body')]
    [System.Int32]
    # .
    ${HostUsageScaleCriteriaScaleOutHostChangeCount},

    [Parameter(ParameterSetName='SetExpanded')]
    [NmePowershell.Category('Body')]
    [System.Single]
    # .
    ${HostUsageScaleCriteriaScaleOutValue},

    [Parameter(ParameterSetName='SetExpanded')]
    [NmePowershell.PSArgumentCompleterAttribute("DepthFirst", "BreadthFirst")]
    [NmePowershell.Category('Body')]
    [System.String]
    # .
    ${NetworkDistributionStrategy},

    [Parameter(ParameterSetName='SetExpanded')]
    [AllowEmptyCollection()]
    [NmePowershell.Category('Body')]
    [NmePowershell.Models.IPreStageHostsConfigurationItem[]]
    # .
    ${PreStageHostConfigs},

    [Parameter(ParameterSetName='SetExpanded')]
    [NmePowershell.PSArgumentCompleterAttribute("Hybrid", "Automated")]
    [NmePowershell.Category('Body')]
    [System.String]
    # .
    ${PreStageHostIntelligentPrestageMode},

    [Parameter(ParameterSetName='SetExpanded')]
    [NmePowershell.Category('Body')]
    [System.Management.Automation.SwitchParameter]
    # .
    ${PreStageHostIsMultipleConfigsMode},

    [Parameter(ParameterSetName='SetExpanded')]
    [NmePowershell.Category('Body')]
    [System.String]
    # .
    ${RemoveMessagingMessage},

    [Parameter(ParameterSetName='SetExpanded')]
    [NmePowershell.Category('Body')]
    [System.Int32]
    # .
    ${RemoveMessagingMinutesBeforeRemove},

    [Parameter(ParameterSetName='SetExpanded')]
    [NmePowershell.Category('Body')]
    [System.Management.Automation.SwitchParameter]
    # .
    ${RollingDrainModeIsEnabled},

    [Parameter(ParameterSetName='SetExpanded')]
    [AllowEmptyCollection()]
    [NmePowershell.Category('Body')]
    [NmePowershell.Models.IRollingDrainModeWindow[]]
    # .
    ${RollingDrainModeWindows},

    [Parameter(ParameterSetName='SetExpanded')]
    [NmePowershell.Category('Body')]
    [System.Int32]
    # .
    ${ScaleInAverageTimeRangeInMinutes},

    [Parameter(ParameterSetName='SetExpanded')]
    [NmePowershell.Category('Body')]
    [System.Int32]
    # .
    ${ScaleOutAverageTimeRangeInMinutes},

    [Parameter(ParameterSetName='SetExpanded')]
    [NmePowershell.Category('Body')]
    [System.Management.Automation.SwitchParameter]
    # .
    ${SecondaryRegionEnabled},

    [Parameter(ParameterSetName='SetExpanded')]
    [NmePowershell.Category('Body')]
    [System.Int32]
    # .
    ${StartWorkDuration},

    [Parameter(ParameterSetName='SetExpanded')]
    [NmePowershell.Category('Body')]
    [System.Int32]
    # .
    ${StartWorkHour},

    [Parameter(ParameterSetName='SetExpanded')]
    [NmePowershell.Category('Body')]
    [System.Int32]
    # .
    ${StartWorkMinutes},

    [Parameter(ParameterSetName='SetExpanded')]
    [NmePowershell.Category('Body')]
    [System.String]
    # .
    ${StoppedDiskType},

    [Parameter(ParameterSetName='SetExpanded')]
    [NmePowershell.Category('Body')]
    [System.Int32]
    # .
    ${TimeRangeEndHour},

    [Parameter(ParameterSetName='SetExpanded')]
    [NmePowershell.Category('Body')]
    [System.Int32]
    # .
    ${TimeRangeEndMinutes},

    [Parameter(ParameterSetName='SetExpanded')]
    [NmePowershell.Category('Body')]
    [System.Int32]
    # .
    ${TimeRangeStartHour},

    [Parameter(ParameterSetName='SetExpanded')]
    [NmePowershell.Category('Body')]
    [System.Int32]
    # .
    ${TimeRangeStartMinutes},

    [Parameter(ParameterSetName='SetExpanded')]
    [NmePowershell.Category('Body')]
    [System.String]
    # .
    ${TimezoneId},

    [Parameter(ParameterSetName='SetExpanded')]
    [NmePowershell.Category('Body')]
    [System.Management.Automation.SwitchParameter]
    # .
    ${UserDrivenBypassDrainMode},

    [Parameter(ParameterSetName='SetExpanded')]
    [NmePowershell.Category('Body')]
    [System.Int32]
    # .
    ${UserDrivenMinAvailableSessions},

    [Parameter(ParameterSetName='SetExpanded')]
    [AllowEmptyCollection()]
    [NmePowershell.Category('Body')]
    [NmePowershell.Models.IUserDrivenPreStageHostsConfigurationItem[]]
    # .
    ${UserDrivenPreStageHostConfigs},

    [Parameter(ParameterSetName='SetExpanded')]
    [NmePowershell.Category('Body')]
    [System.Management.Automation.SwitchParameter]
    # .
    ${UserDrivenPreStageHostEnable},

    [Parameter(ParameterSetName='SetExpanded')]
    [NmePowershell.Category('Body')]
    [System.Management.Automation.SwitchParameter]
    # .
    ${UserDrivenPreStageHostPreStageIfUnassigned},

    [Parameter(ParameterSetName='SetExpanded')]
    [NmePowershell.Category('Body')]
    [System.Int32]
    # .
    ${UserDrivenStopDelayMinutes},

    [Parameter(ParameterSetName='SetExpanded')]
    [NmePowershell.PSArgumentCompleterAttribute("Standard", "Reuse", "Unique")]
    [NmePowershell.Category('Body')]
    [System.String]
    # .
    ${VMNamingMode},

    [Parameter(ParameterSetName='SetExpanded')]
    [NmePowershell.Category('Body')]
    [System.String]
    # .
    ${VMTemplateDiskPerformanceTier},

    [Parameter(ParameterSetName='SetExpanded')]
    [NmePowershell.Category('Body')]
    [System.Int32]
    # .
    ${VMTemplateDiskSize},

    [Parameter(ParameterSetName='SetExpanded')]
    [NmePowershell.PSArgumentCompleterAttribute("CacheDisk", "ResourceDisk", "NvmeDisk")]
    [NmePowershell.Category('Body')]
    [System.String]
    # .
    ${VMTemplateEphemeralOsdiskPlacement},

    [Parameter(ParameterSetName='SetExpanded')]
    [NmePowershell.Category('Body')]
    [System.Management.Automation.SwitchParameter]
    # .
    ${VMTemplateHasEphemeralOsdisk},

    [Parameter(ParameterSetName='SetExpanded')]
    [NmePowershell.Category('Body')]
    [System.String]
    # .
    ${VMTemplateImage},

    [Parameter(ParameterSetName='SetExpanded')]
    [NmePowershell.Category('Body')]
    [System.String]
    # .
    ${VMTemplateNetworkId},

    [Parameter(ParameterSetName='SetExpanded')]
    [NmePowershell.Category('Body')]
    [System.String]
    # .
    ${VMTemplatePrefix},

    [Parameter(ParameterSetName='SetExpanded')]
    [NmePowershell.Category('Body')]
    [System.String]
    # .
    ${VMTemplateResourceGroupId},

    [Parameter(ParameterSetName='SetExpanded')]
    [NmePowershell.Category('Body')]
    [System.String]
    # .
    ${VMTemplateSize},

    [Parameter(ParameterSetName='SetExpanded')]
    [NmePowershell.Category('Body')]
    [System.String]
    # .
    ${VMTemplateStorageType},

    [Parameter(ParameterSetName='SetExpanded')]
    [NmePowershell.Category('Body')]
    [System.String]
    # .
    ${VMTemplateSubnet},

    [Parameter(ParameterSetName='SetExpanded')]
    [NmePowershell.PSArgumentCompleterAttribute("OneTime", "Continuously", "Never")]
    [NmePowershell.Category('Body')]
    [System.String]
    # .
    ${WorkingHoursScaleInBehavior},

    [Parameter(ParameterSetName='SetExpanded')]
    [NmePowershell.PSArgumentCompleterAttribute("OneTime", "Continuously", "Never")]
    [NmePowershell.Category('Body')]
    [System.String]
    # .
    ${WorkingHoursScaleOutBehavior},

    [Parameter(DontShow)]
    [NmePowershell.Category('Runtime')]
    [System.Management.Automation.SwitchParameter]
    # Wait for .NET debugger to attach
    ${Break},

    [Parameter(DontShow)]
    [ValidateNotNull()]
    [NmePowershell.Category('Runtime')]
    [NmePowershell.Runtime.SendAsyncStep[]]
    # SendAsync Pipeline Steps to be appended to the front of the pipeline
    ${HttpPipelineAppend},

    [Parameter(DontShow)]
    [ValidateNotNull()]
    [NmePowershell.Category('Runtime')]
    [NmePowershell.Runtime.SendAsyncStep[]]
    # SendAsync Pipeline Steps to be prepended to the front of the pipeline
    ${HttpPipelinePrepend},

    [Parameter(DontShow)]
    [NmePowershell.Category('Runtime')]
    [System.Uri]
    # The URI for the proxy server to use
    ${Proxy},

    [Parameter(DontShow)]
    [ValidateNotNull()]
    [NmePowershell.Category('Runtime')]
    [System.Management.Automation.PSCredential]
    # Credentials for a proxy server to use for the remote call
    ${ProxyCredential},

    [Parameter(DontShow)]
    [NmePowershell.Category('Runtime')]
    [System.Management.Automation.SwitchParameter]
    # Use the default credentials for the proxy
    ${ProxyUseDefaultCredentials}
)

begin {
    try {
        $outBuffer = $null
        if ($PSBoundParameters.TryGetValue('OutBuffer', [ref]$outBuffer)) {
            $PSBoundParameters['OutBuffer'] = 1
        }
        $parameterSet = $PSCmdlet.ParameterSetName
        
        $testPlayback = $false
        $PSBoundParameters['HttpPipelinePrepend'] | Foreach-Object { if ($_) { $testPlayback = $testPlayback -or ('NmePowershell.Runtime.PipelineMock' -eq $_.Target.GetType().FullName -and 'Playback' -eq $_.Target.Mode) } }

        $mapping = @{
            Set = 'NerdioManagerPowerShell.private\Set-NmeHostPoolAutoScale_Set';
            SetExpanded = 'NerdioManagerPowerShell.private\Set-NmeHostPoolAutoScale_SetExpanded';
        }
        $cmdInfo = Get-Command -Name $mapping[$parameterSet]
        [NmePowershell.Runtime.MessageAttributeHelper]::ProcessCustomAttributesAtRuntime($cmdInfo, $MyInvocation, $parameterSet, $PSCmdlet)
        [NmePowershell.Runtime.MessageAttributeHelper]::ProcessPreviewMessageAttributesAtRuntime($cmdInfo, $MyInvocation, $parameterSet, $PSCmdlet)
        $wrappedCmd = $ExecutionContext.InvokeCommand.GetCommand(($mapping[$parameterSet]), [System.Management.Automation.CommandTypes]::Cmdlet)
        if ($wrappedCmd -eq $null) {
            $wrappedCmd = $ExecutionContext.InvokeCommand.GetCommand(($mapping[$parameterSet]), [System.Management.Automation.CommandTypes]::Function)
        }
        $scriptCmd = {& $wrappedCmd @PSBoundParameters}
        $steppablePipeline = $scriptCmd.GetSteppablePipeline($MyInvocation.CommandOrigin)
        $steppablePipeline.Begin($PSCmdlet)
    } catch {

        throw
    }
}

process {
    try {
        $steppablePipeline.Process($_)
    } catch {

        throw
    }

}
end {
    try {
        $steppablePipeline.End()

    } catch {

        throw
    }
} 
}
