
# ----------------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.10.8, generator: @autorest/powershell@4.0.752)
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# ----------------------------------------------------------------------------------

<#
.Synopsis
Set Active Directory configuration for ARM host pool
.Description
Set Active Directory configuration for ARM host pool

#>
function Set-NmeHostPoolActiveDirectoryConfiguration {
[OutputType([NmePowershell.Models.IHostPoolActiveDirectory])]
[CmdletBinding(DefaultParameterSetName='SetExpanded', PositionalBinding=$false, SupportsShouldProcess, ConfirmImpact='Medium')]
param(
    [Parameter(Mandatory)]
    [NmePowershell.Category('Path')]
    [System.String]
    # .
    ${HostPoolName},

    [Parameter(Mandatory)]
    [NmePowershell.Category('Path')]
    [System.String]
    # .
    ${ResourceGroup},

    [Parameter(Mandatory)]
    [NmePowershell.Category('Path')]
    [System.String]
    # .
    ${SubscriptionId},

    [Parameter(ParameterSetName='Set', Mandatory, ValueFromPipeline)]
    [NmePowershell.Category('Body')]
    [NmePowershell.Models.IHostPoolActiveDirectoryUpdate]
    # .
    ${Body},

    [Parameter(ParameterSetName='SetExpanded', Mandatory)]
    [NmePowershell.PSArgumentCompleterAttribute("Default", "Predefined", "Custom")]
    [NmePowershell.Category('Body')]
    [System.String]
    # .
    ${Type},

    [Parameter(ParameterSetName='SetExpanded')]
    [NmePowershell.PSArgumentCompleterAttribute("AD", "AzureAD", "AzureADDS")]
    [NmePowershell.Category('Body')]
    [System.String]
    # .
    ${CustomAdIdentityType},

    [Parameter(ParameterSetName='SetExpanded')]
    [NmePowershell.Category('Body')]
    [System.String]
    # .
    ${CustomDomain},

    [Parameter(ParameterSetName='SetExpanded')]
    [NmePowershell.Category('Body')]
    [System.Management.Automation.SwitchParameter]
    # .
    ${CustomEnrollWithIntune},

    [Parameter(ParameterSetName='SetExpanded')]
    [NmePowershell.Category('Body')]
    [System.String]
    # .
    ${CustomFriendlyName},

    [Parameter(ParameterSetName='SetExpanded')]
    [NmePowershell.Category('Body')]
    [System.String]
    # .
    ${CustomOrganizationUnit},

    [Parameter(ParameterSetName='SetExpanded')]
    [NmePowershell.Category('Body')]
    [System.String]
    # .
    ${CustomPassword},

    [Parameter(ParameterSetName='SetExpanded')]
    [NmePowershell.Category('Body')]
    [System.String]
    # .
    ${CustomUsername},

    [Parameter(ParameterSetName='SetExpanded')]
    [NmePowershell.Category('Body')]
    [System.Int32]
    # .
    ${PredefinedConfigId},

    [Parameter(DontShow)]
    [NmePowershell.Category('Runtime')]
    [System.Management.Automation.SwitchParameter]
    # Wait for .NET debugger to attach
    ${Break},

    [Parameter(DontShow)]
    [ValidateNotNull()]
    [NmePowershell.Category('Runtime')]
    [NmePowershell.Runtime.SendAsyncStep[]]
    # SendAsync Pipeline Steps to be appended to the front of the pipeline
    ${HttpPipelineAppend},

    [Parameter(DontShow)]
    [ValidateNotNull()]
    [NmePowershell.Category('Runtime')]
    [NmePowershell.Runtime.SendAsyncStep[]]
    # SendAsync Pipeline Steps to be prepended to the front of the pipeline
    ${HttpPipelinePrepend},

    [Parameter(DontShow)]
    [NmePowershell.Category('Runtime')]
    [System.Uri]
    # The URI for the proxy server to use
    ${Proxy},

    [Parameter(DontShow)]
    [ValidateNotNull()]
    [NmePowershell.Category('Runtime')]
    [System.Management.Automation.PSCredential]
    # Credentials for a proxy server to use for the remote call
    ${ProxyCredential},

    [Parameter(DontShow)]
    [NmePowershell.Category('Runtime')]
    [System.Management.Automation.SwitchParameter]
    # Use the default credentials for the proxy
    ${ProxyUseDefaultCredentials}
)

begin {
    try {
        $outBuffer = $null
        if ($PSBoundParameters.TryGetValue('OutBuffer', [ref]$outBuffer)) {
            $PSBoundParameters['OutBuffer'] = 1
        }
        $parameterSet = $PSCmdlet.ParameterSetName
        
        $testPlayback = $false
        $PSBoundParameters['HttpPipelinePrepend'] | Foreach-Object { if ($_) { $testPlayback = $testPlayback -or ('NmePowershell.Runtime.PipelineMock' -eq $_.Target.GetType().FullName -and 'Playback' -eq $_.Target.Mode) } }

        $mapping = @{
            Set = 'NerdioManagerPowerShell.private\Set-NmeHostPoolActiveDirectoryConfiguration_Set';
            SetExpanded = 'NerdioManagerPowerShell.private\Set-NmeHostPoolActiveDirectoryConfiguration_SetExpanded';
        }
        $cmdInfo = Get-Command -Name $mapping[$parameterSet]
        [NmePowershell.Runtime.MessageAttributeHelper]::ProcessCustomAttributesAtRuntime($cmdInfo, $MyInvocation, $parameterSet, $PSCmdlet)
        [NmePowershell.Runtime.MessageAttributeHelper]::ProcessPreviewMessageAttributesAtRuntime($cmdInfo, $MyInvocation, $parameterSet, $PSCmdlet)
        $wrappedCmd = $ExecutionContext.InvokeCommand.GetCommand(($mapping[$parameterSet]), [System.Management.Automation.CommandTypes]::Cmdlet)
        if ($wrappedCmd -eq $null) {
            $wrappedCmd = $ExecutionContext.InvokeCommand.GetCommand(($mapping[$parameterSet]), [System.Management.Automation.CommandTypes]::Function)
        }
        $scriptCmd = {& $wrappedCmd @PSBoundParameters}
        $steppablePipeline = $scriptCmd.GetSteppablePipeline($MyInvocation.CommandOrigin)
        $steppablePipeline.Begin($PSCmdlet)
    } catch {

        throw
    }
}

process {
    try {
        $steppablePipeline.Process($_)
    } catch {

        throw
    }

}
end {
    try {
        $steppablePipeline.End()

    } catch {

        throw
    }
} 
}
