
# ----------------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.10.8, generator: @autorest/powershell@4.0.752)
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# ----------------------------------------------------------------------------------

<#
.Synopsis
Update ControlUp properties for ARM host pool
.Description
Update ControlUp properties for ARM host pool

#>
function Update-NmeHostPoolControlUpProperty {
[OutputType([NmePowershell.Models.IHostPoolControlUp])]
[CmdletBinding(DefaultParameterSetName='UpdateExpanded', PositionalBinding=$false, SupportsShouldProcess, ConfirmImpact='Medium')]
param(
    [Parameter(Mandatory)]
    [NmePowershell.Category('Path')]
    [System.String]
    # .
    ${HostPoolName},

    [Parameter(Mandatory)]
    [NmePowershell.Category('Path')]
    [System.String]
    # .
    ${ResourceGroup},

    [Parameter(Mandatory)]
    [NmePowershell.Category('Path')]
    [System.String]
    # .
    ${SubscriptionId},

    [Parameter(ParameterSetName='Update', Mandatory, ValueFromPipeline)]
    [NmePowershell.Category('Body')]
    [NmePowershell.Models.IHostPoolControlUpUpdate]
    # .
    ${Body},

    [Parameter(ParameterSetName='UpdateExpanded')]
    [NmePowershell.Category('Body')]
    [System.Management.Automation.SwitchParameter]
    # .
    ${AuthenticationDefault},

    [Parameter(ParameterSetName='UpdateExpanded')]
    [NmePowershell.Category('Body')]
    [System.String]
    # .
    ${AuthenticationValue},

    [Parameter(ParameterSetName='UpdateExpanded')]
    [NmePowershell.Category('Body')]
    [System.String]
    # .
    ${DnsZone},

    [Parameter(ParameterSetName='UpdateExpanded')]
    [NmePowershell.Category('Body')]
    [System.String]
    # .
    ${Folder},

    [Parameter(ParameterSetName='UpdateExpanded')]
    [NmePowershell.Category('Body')]
    [System.Management.Automation.SwitchParameter]
    # .
    ${IsEnabled},

    [Parameter(ParameterSetName='UpdateExpanded')]
    [AllowEmptyCollection()]
    [NmePowershell.PSArgumentCompleterAttribute("0", "1", "2", "3", "4", "5", "6")]
    [NmePowershell.Category('Body')]
    [System.Int32[]]
    # .
    ${MaintenanceWindowDays},

    [Parameter(ParameterSetName='UpdateExpanded')]
    [NmePowershell.Category('Body')]
    [System.Int32]
    # .
    ${MaintenanceWindowDurationMinutes},

    [Parameter(ParameterSetName='UpdateExpanded')]
    [NmePowershell.Category('Body')]
    [System.Management.Automation.SwitchParameter]
    # .
    ${MaintenanceWindowEnabled},

    [Parameter(ParameterSetName='UpdateExpanded')]
    [NmePowershell.Category('Body')]
    [System.Int32]
    # .
    ${MaintenanceWindowStartHour},

    [Parameter(ParameterSetName='UpdateExpanded')]
    [NmePowershell.Category('Body')]
    [System.Int32]
    # .
    ${MaintenanceWindowStartMinutes},

    [Parameter(ParameterSetName='UpdateExpanded')]
    [NmePowershell.Category('Body')]
    [System.String]
    # .
    ${MaintenanceWindowTimezoneId},

    [Parameter(ParameterSetName='UpdateExpanded')]
    [NmePowershell.Category('Body')]
    [System.Int32]
    # .
    ${MaxJobs},

    [Parameter(ParameterSetName='UpdateExpanded')]
    [AllowEmptyCollection()]
    [NmePowershell.Category('Body')]
    [System.String[]]
    # .
    ${Monitors},

    [Parameter(ParameterSetName='UpdateExpanded')]
    [NmePowershell.PSArgumentCompleterAttribute("Disabled", "Default", "Custom")]
    [NmePowershell.Category('Body')]
    [System.String]
    # .
    ${RegistrationType},

    [Parameter(ParameterSetName='UpdateExpanded')]
    [NmePowershell.Category('Body')]
    [System.String]
    # .
    ${RegistrationValue},

    [Parameter(ParameterSetName='UpdateExpanded')]
    [NmePowershell.Category('Body')]
    [System.String]
    # .
    ${SecondaryDnsZone},

    [Parameter(ParameterSetName='UpdateExpanded')]
    [NmePowershell.Category('Body')]
    [System.Management.Automation.SwitchParameter]
    # .
    ${SecondaryEnabled},

    [Parameter(ParameterSetName='UpdateExpanded')]
    [NmePowershell.Category('Body')]
    [System.String]
    # .
    ${SecondaryFolder},

    [Parameter(ParameterSetName='UpdateExpanded')]
    [AllowEmptyCollection()]
    [NmePowershell.Category('Body')]
    [System.String[]]
    # .
    ${SecondaryMonitors},

    [Parameter(ParameterSetName='UpdateExpanded')]
    [NmePowershell.Category('Body')]
    [System.String]
    # .
    ${SecondarySite},

    [Parameter(ParameterSetName='UpdateExpanded')]
    [NmePowershell.Category('Body')]
    [System.String]
    # .
    ${Site},

    [Parameter(ParameterSetName='UpdateExpanded')]
    [NmePowershell.Category('Body')]
    [System.Management.Automation.SwitchParameter]
    # .
    ${UnjoinHosts},

    [Parameter(ParameterSetName='UpdateExpanded')]
    [NmePowershell.Category('Body')]
    [System.Int32]
    # .
    ${UnjoinHostsDelayInDays},

    [Parameter(ParameterSetName='UpdateExpanded')]
    [NmePowershell.Category('Body')]
    [System.Management.Automation.SwitchParameter]
    # .
    ${UseDefault},

    [Parameter(ParameterSetName='UpdateExpanded')]
    [NmePowershell.Category('Body')]
    [System.String]
    # .
    ${Version},

    [Parameter(DontShow)]
    [NmePowershell.Category('Runtime')]
    [System.Management.Automation.SwitchParameter]
    # Wait for .NET debugger to attach
    ${Break},

    [Parameter(DontShow)]
    [ValidateNotNull()]
    [NmePowershell.Category('Runtime')]
    [NmePowershell.Runtime.SendAsyncStep[]]
    # SendAsync Pipeline Steps to be appended to the front of the pipeline
    ${HttpPipelineAppend},

    [Parameter(DontShow)]
    [ValidateNotNull()]
    [NmePowershell.Category('Runtime')]
    [NmePowershell.Runtime.SendAsyncStep[]]
    # SendAsync Pipeline Steps to be prepended to the front of the pipeline
    ${HttpPipelinePrepend},

    [Parameter(DontShow)]
    [NmePowershell.Category('Runtime')]
    [System.Uri]
    # The URI for the proxy server to use
    ${Proxy},

    [Parameter(DontShow)]
    [ValidateNotNull()]
    [NmePowershell.Category('Runtime')]
    [System.Management.Automation.PSCredential]
    # Credentials for a proxy server to use for the remote call
    ${ProxyCredential},

    [Parameter(DontShow)]
    [NmePowershell.Category('Runtime')]
    [System.Management.Automation.SwitchParameter]
    # Use the default credentials for the proxy
    ${ProxyUseDefaultCredentials}
)

begin {
    try {
        $outBuffer = $null
        if ($PSBoundParameters.TryGetValue('OutBuffer', [ref]$outBuffer)) {
            $PSBoundParameters['OutBuffer'] = 1
        }
        $parameterSet = $PSCmdlet.ParameterSetName
        
        $testPlayback = $false
        $PSBoundParameters['HttpPipelinePrepend'] | Foreach-Object { if ($_) { $testPlayback = $testPlayback -or ('NmePowershell.Runtime.PipelineMock' -eq $_.Target.GetType().FullName -and 'Playback' -eq $_.Target.Mode) } }

        $mapping = @{
            Update = 'NerdioManagerPowerShell.private\Update-NmeHostPoolControlUpProperty_Update';
            UpdateExpanded = 'NerdioManagerPowerShell.private\Update-NmeHostPoolControlUpProperty_UpdateExpanded';
        }
        $cmdInfo = Get-Command -Name $mapping[$parameterSet]
        [NmePowershell.Runtime.MessageAttributeHelper]::ProcessCustomAttributesAtRuntime($cmdInfo, $MyInvocation, $parameterSet, $PSCmdlet)
        [NmePowershell.Runtime.MessageAttributeHelper]::ProcessPreviewMessageAttributesAtRuntime($cmdInfo, $MyInvocation, $parameterSet, $PSCmdlet)
        $wrappedCmd = $ExecutionContext.InvokeCommand.GetCommand(($mapping[$parameterSet]), [System.Management.Automation.CommandTypes]::Cmdlet)
        if ($wrappedCmd -eq $null) {
            $wrappedCmd = $ExecutionContext.InvokeCommand.GetCommand(($mapping[$parameterSet]), [System.Management.Automation.CommandTypes]::Function)
        }
        $scriptCmd = {& $wrappedCmd @PSBoundParameters}
        $steppablePipeline = $scriptCmd.GetSteppablePipeline($MyInvocation.CommandOrigin)
        $steppablePipeline.Begin($PSCmdlet)
    } catch {

        throw
    }
}

process {
    try {
        $steppablePipeline.Process($_)
    } catch {

        throw
    }

}
end {
    try {
        $steppablePipeline.End()

    } catch {

        throw
    }
} 
}
